### PR TITLE
chore(ci): upgrade kubernetes API to 1.29

### LINKED ISSUE #5307: Bump kubernetes dependencies to 1.29
### Requirement

As per $subject

### Problem

a

### Proposal

_No response_

### Open questions

_No response_

### PR DESCRIPTION
**Pull request by squakez**
Closes #5307

**Release Note**
```release-note
chore(ci): upgrade kubernetes API to 1.29
```

### CODE REVIEW

**Review by gansheer — COMMENTED** [review]
You are missing the upgrade to the azure/setup-kubectl@v4 github action.

**Comment by squakez** [comment]
> You are missing the upgrade to the azure/setup-kubectl@v4 github action.

Thanks, I'll take care of it. Any reason why this one is not on default setting (latest?). In theory the latest should be compatible with a few version before, so we could simplify our API upgrade process.

**Comment by gansheer** [comment]
> > You are missing the upgrade to the azure/setup-kubectl@v4 github action.
> 
> Thanks, I'll take care of it. Any reason why this one is not on default setting (latest?). In theory the latest should be compatible with a few version before, so we could simplify our API upgrade process.

No idea, it might be an old configuration.

**Comment by gansheer** [comment]
Ha and I forgot, there is also the kindest/node image in `.github/actions/kamel-config-cluster-custom/action.yml` to be adapted (https://github.com/kubernetes-sigs/kind/releases)

**Pull request merged**
