### PR TITLE
test(health): #3997 structured conditions for scaled integrations

### PR DESCRIPTION
**Pull request by rinaldodev**
https://github.com/apache/camel-k/issues/3997

### CODE REVIEW

**Comment by rinaldodev** [comment]
@squakez I was considering adding tests for more scenarios. Do you think its worth it?

**Review by oscerd — APPROVED** [review]

**Comment by squakez** [comment]
> @squakez I was considering adding tests for more scenarios. Do you think its worth it?

The more scenario we cover the better. However, for the specific issue I think it should be fine.

**Comment by squakez** [comment]
Feel free to move the PR to ready to review or add a comment when you are okey to merge it.

**Review by lburgazzoli — APPROVED** [review]

**Comment by rinaldodev** [comment]
> Feel free to move the PR to ready to review or add a comment when you are okey to merge it.

Thanks, I will. Some of the tests are flaky and I'm trying to figure out why.

**Comment by rinaldodev** [comment]
> Thanks, I will. Some of the tests are flaky and I'm trying to figure out why.

Some of the original tests are flaky because sometimes routes are considered UP for a while before being reported as DOWN. Since this PR is now open for some time, I'll look for a fix in a different issue/PR.

**Pull request merged**
