### PR TITLE
Change master trait to use camel-quarkus-kubernetes

### PR DESCRIPTION
**Pull request by claudio4j**
https://github.com/apache/camel-k/issues/4048

This migration to use camel-quarkus-kubernetes required breaking changes to the master trait, as camel-quarkus-kubernetes requires build time properties. It was not possible to set the build time properties from the master trait in Integration phase as it is managed by the IntegrationController and the build time properties is managed by IntegrationKitController, and the latter one doesn't have the Integration object.

So, from an Integration perspective the migration to use this master trait is:

Before migration:
```
-t master.resource-name=foobar
```

After migration:
```
--build-property quarkus.camel.cluster.kubernetes.resource-name=foobar
```

The [accompanying camel-k-runtime change to remove the camel-k-master component](https://github.com/apache/camel-k-runtime/pull/982).

**Release Note**
```release-note
master trait: use build time properties from camel-quarkus-kubernetes (breaking change)
```

### CODE REVIEW

**Review by squakez — COMMENTED** [review]
In my opinion we should remove this trait at all. The most evident reason is the fact that, by doing this change we're coupling this trait to the final runtime implementation. As we're talking to allow in the future any Camel application, this could be an important constraint.

How much would it be complicated to setup a master functionality without a trait? If I am understanding it correctly, we should have the same result by providing certain dependencies and a series of built-time properties. At the end of the day, a trait is just syntactic sugar, so, if we can have a feature simple enough without a trait, this has no longer any sense IMO.

**Comment by claudio4j** [comment]
> we should have the same result by providing certain dependencies and a series of built-time properties. At the end of the day, a trait is just syntactic sugar

That's true. Not having the master trait, the required actions the user must perform:
- provide the required dependencies with `-d camel:<component name>`
- [set the rbac permissions for the ServiceAccount](https://github.com/apache/camel-k/tree/main/resources/addons/master) to handle either `Lease` or `ConfigMap` 

The traits automation in general help users to deal with the boring setup, I would say this automation is good for camel K, at the cost of having the coupling you mentioned.

**Comment by lburgazzoli** [comment]
I guess this is could be part of the capabilities/contract we were talking in the past ?  
Like we could keep the trait and the runtime can provide the related implementation.
Ideally if a runtime does not support the master trait, then it can advertise it in the catalog ?

**Comment by squakez** [comment]
I wonder if it is okey if we have the SA already set with those permissions OOTB and be able to use the components directly without a trait then.

**Comment by squakez** [comment]
> I guess this is could be part of the capabilities/contract we were talking in the past ? Like we could keep the trait and the runtime can provide the related implementation. Ideally if a runtime does not support the master trait, then it can advertise it in the catalog ?

Yes, that would be part of the catalog, good point.

**Comment by lburgazzoli** [comment]
> #4048
> 
> This migration to use camel-quarkus-kubernetes required breaking changes to the master trait, as camel-quarkus-kubernetes requires build time properties. It was not possible to set the build time properties from the master trait in Integration phase as it is managed by the IntegrationController and the build time properties is managed by IntegrationKitController, and the latter one doesn't have the Integration object.
> 

I'm wondering why those are build time properties, like, the resource key must be something configurable at runtime. Other can be probably be build time and we can be opinionated.

**Comment by lburgazzoli** [comment]
> > I guess this is could be part of the capabilities/contract we were talking in the past ? Like we could keep the trait and the runtime can provide the related implementation. Ideally if a runtime does not support the master trait, then it can advertise it in the catalog ?
> 
> It seems I missed this previous discussion, but looking at the camel-k-runtime catalog, it appears the capabilities are a set of dependencies for each capability. Is there anything more ?

not at this stage but we can maybe use the lack of a capability as a way to advertise such capability is not supported

**Comment by squakez** [comment]
@claudio4j we have discussed this possibility in the 2023 roadmap: https://camel.apache.org/blog/2023/02/camel-k-roadmap-2023/ (Enhance build and make it more “enterprise” paragraph). Some first draft design was provided in https://github.com/apache/camel-k/issues/4024 as well.

**Comment by claudio4j** [comment]
I will rebase and fix the e2e master trait test

**Comment by squakez** [comment]
> I will rebase and fix the e2e master trait test

Please, consider @lburgazzoli suggestions maybe having back the implementation (or part of it) in the runtime in order to make Camel K not dependent on any runtime specific requirements. I'd take the opportunity to think on a simpler design if you see it makes sense in the light of the new changes introduced in Camel Quarkus.

**Pull request closed without merging**
