### PR TITLE
fix: Panic with odd number of key / value arguments

### PR DESCRIPTION
**Pull request by astefanutti**
**Release Note**
```release-note
fix: Panic with odd number of key / value arguments
```

### CODE REVIEW

**Review by essobedo — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by astefanutti** [comment]
The CI failures are unrelated. Let me merge this.

**Comment by tadayosi** [comment]
@astefanutti Validation started to fail from here.

**Comment by tadayosi** [comment]
It's baffling but indeed reverting the commit clear the validate failure.
https://github.com/tadayosi/camel-k/runs/8106868130?check_suite_focus=true
Possibly it's just the last straw for something with linting?  Anyway we'd like to remove the linting failure in any way.

**Comment by astefanutti** [comment]
@tadayosi yes, these are new issues unrelated to that PR. Maybe we'll want to add `only-new-issues: true` to the golangci-lint action configuration.

**Pull request merged**
