### PR TITLE
[wip] Fixes #889, added DeleteFunc for integration, kit and build controllers to cleanup generated resources

### LINKED ISSUE #889: Camel-K operator should clean up kits and kit builders after integrations are deleted
Now that adding a new integration creates a `camel-k-kit-*` and `camel-k-kit-*-builder` along with the integration pod itself, it seems there should be some clean up to remove those when the integration is deleted? I'm seeing the custom resource/integrationkits still hanging around after I remove the integrations.

### PR DESCRIPTION
**Pull request by dhirajsb**
**Release Note**
Deleting an integration now deletes builds, buildconfigs, and build pods, and deleting an integrationkit deletes imagestreams.
```release-note
NONE
```

### CODE REVIEW

**Comment by dhirajsb** [comment]
@nicolaferraro do you know why the buildah tests are failing? I can't tell from the logs whether it's something broken in the PR or the test environment.

**Comment by nicolaferraro** [comment]
> @nicolaferraro do you know why the buildah tests are failing? I can't tell from the logs whether it's something broken in the PR or the test environment.

I've refactored the tests and (hopefully) fixed the CI. The main problem was due Github action recent changes that cached a lot of container images in the default base image, using all the space.

**Comment by nicolaferraro** [comment]
You can try to rebase to test again

**Comment by dhirajsb** [comment]
cool, the integration tests are passing, looks like the Travis CI test failed because it couldn't download openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz. 

I'm working on revising this PR anyway, so I'll check it once my changes are done.

**Comment by nicolaferraro** [comment]
@dhirajsb do you still need to revisit this or you think it's ok?

**Pull request closed without merging**
