### PR TITLE
Enable parsing pod template as a modeline.

### PR DESCRIPTION
**Pull request by ammachado**
A patch to allow pod templates in json to be declared in modelines.

As it is today, this does not work:

```java
// camel-k: pod-template='{ "containers": [], "securityContext": { "supplementalGroups": [ 553 ] }, "volumes": [] } }'
```

but this does:

```java
// camel-k: pod-template={"containers":[],"securityContext":{"supplementalGroups":[553]},"volumes":[]}}
```

**Release Note**
```release-note
Enable parsing pod template as a modeline
```

### CODE REVIEW

**Review by squakez — APPROVED** [review]
Nice, thanks! Just some minor change is required to pass static code analysis.

**Comment by ammachado** [comment]
I'm doing some tests here, and Camel-K is ignoring the `securityContext` part of my pod template:

```yaml
containers:
- name: integration
    volumeMounts:
      - name: apptestpvc
        mountPath: /mnt/shared
volumes:
  - name: apptestpvc
    persistentVolumeClaim:
      claimName: apptestpvc
securityContext:
  supplementalGroups:
    - 606
```

Looking on the [camel.apache.org_integrations.yaml](https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_integrations.yaml) file, and it does not specifies the `supplementalGroups` property, which in my case is needed to apply a volume mount permission.

Also this is not configurable by using the `kamel` command line, just by editing the integration.

Is that correct?

**Comment by squakez** [comment]
I'm merging this as it looks fine. About the last comment, @ammachado please, open a new issue asking the same question, I think it may be not related to this PR.

**Comment by ammachado** [comment]
There's a PR for that: #3330.

**Pull request merged**
