### PR TITLE
Update operator-sdk and operator-lifecycle-manager

### PR DESCRIPTION
**Pull request by akihikokuroda**
This PR is the fix for #2067 in master branch. It upgrades the operator-lifecycle-manager to v0.17.0 and operator-sdk to v1.0.0 to remove the bou.ke/monkey dependency.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by astefanutti** [comment]
I'd suggest to apply the transitioning from `github.com/operator-framework/operator-lifecycle-manager` to `github.com/operator-framework/api` on top of  #2076, as the later removes the dependency from the Service Binding operator.

**Comment by astefanutti** [comment]
I've went ahead and integrated the proposed changes into #2076. I think it's the way forward on master branch, so that the dependency on operator-sdk and operator-lifecycle-manager are removed. Let me know if that's ok with you.

**Comment by akihikokuroda** [comment]
Yes, it's good.  I didn't know how far it should go.  Thanks!

**Comment by astefanutti** [comment]
Thanks @akihikokuroda. Let me close this then and follow up on #2067 for the master branch.

**Pull request closed without merging**
