### PR TITLE
fix(#3705) Fix misleading message when updating unchanged integration

### PR DESCRIPTION
**Pull request by bouskaJ**
fix https://github.com/apache/camel-k/issues/3705

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by bouskaJ** [comment]
I slightly modified the code (to satisfy `e2e` tests) and provided a new unit test for this feature. I hope that the CI will pass this time.

**Comment by squakez** [comment]
Please, mind the formatting as reported by the Validate check.

**Comment by bouskaJ** [comment]
> Please, mind the formatting as reported by the Validate check.

Fixed. I always forget to check the code formating 💩 .

**Comment by squakez** [comment]
Please, rebase as we solved the github actions issue.

**Pull request merged**
