### PR TITLE
fix(#1980): Support data types in Kamelets

### LINKED ISSUE #1980: Add support for multiple data types and schemas in Kamelets
Seeking for help on improving the Kamelet model before going full on the Kamelet catalog effort.

Currently the model expects that one declares the default input/output of a Kamelet in the `spec` -> `types` -> `in` / `out` field, like:

```yaml
# ...
  types:
    out:
      mediaType: application/json
      schema:
        #...
```

The same for Kamelets that consume an input, but the property is named `in`.

The meaning of those types is simply stated:
- A Kamelet produces output with the format specified in `out`
- A Kamelet consumes an input with the format specified in `in`

That has unfortunately some drawbacks, one of which is that a Kamelet must have a single data type as output (for sources) and/or a single data type for input.
Many implementations of Kamelets that produce JSON data, in fact, have the following route snippet in the flow part so far:

```yaml
# ...
      steps:
      - marshal:
          json: {}
```

So e.g., if we go full with the Kamelet catalog and add support for them in camel-kafka-connector, I expect soon to have a `salesforce-source-json` and a `salesforce-source-avro` to overcome this limitation. But it's not ideal.

I think we should allow a Kamelet to have a default input/output format, without forcing users to use that one: they may have choices.

I was thinking to something like this:

```yaml
# ...
  types:
    out:
      mediaType: application/json
      schema:
        #...
      camel:
        dataFormat: json-jackson
```

The `dataFormat` option tells the operator to automatically add `camel:jackson` and the marshalling step when the Kamelet is used in a KameletBinding.

For `in`, this translates into:

```yaml
# ...
  types:
    in:
      mediaType: application/json
      schema:
        #...
      camel:
        dataFormat: json-jackson
        className: org.apache.camel.xxx.MyClass
```

This should add the unmarshalling to a specific (optional) class.

In case we want this behavior to be common for KameletBinding and standard integration, **this should be better implemented at runtime level**.

Now the question is how to deal with the case of multiple input/output data types.

A possibility would be to add another level of description:

```yaml
# ...
  types:
    out:
      default: json
      json:
        mediaType: application/json
        schema:
          # the JSON schema
        camel:
          dataFormat: json-jackson
      avro:
        mediaType: application/avro
        schema:
          # the Avro schema
        camel:
          dataFormat: avro
          className: org.apache.camel.xxx.MyClass
```

That would break a bit the current schema, but it will provide more options in the future.

Having the possibility to choose, a user can specify the **format** option in a KameletBinding (that we're going to reserve, like we did for **id**), to select an input/output format that is different from the default (maybe including `none`, to obtain the original data in advanced use cases).

In case this should work also in the standard integration, we may use the following syntax:

```
from("kamelet:salesforce-source?format=avro").to("....")
```

From the operator side, the required libraries for Avro will be added, but the runtime should enhance the route with a loader/customizer.

Wdyt @lburgazzoli, @astefanutti , @davsclaus, @squakez

### PR DESCRIPTION
**Pull request by christophd**
- Adds input/output/error data type spec to Kamelet CRD. The data type specifications provides additional information to the user such as what kind of input is required to use a Kamelet and what output is produced by the Kamelet.
- The data type specifications can be used by tooling and data type converters to improve the overall usability of Kamelets
- Deprecate former types field and EventTypeSpec

Fixes #1980 

Sample source Kamelet using the new dataTypes structure:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: event-source
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Event"
    description: "Source uses different output data types"
    required:
      - token
    properties:
      token:
        title: Token
        description: The authentication token
        type: string
  dataTypes:
    out:
      headers:
        eventId:
          title: "Event Id"
          description: "The id of the event"
          type: string
        eventSubject:
          title: "Event Subject"
          description: "The event subject"
          type: string
      types:
        json:
          mediaType: application/json
          dependencies:
            - camel:jackson
          schema:
            # the JSON schema
        binary:
          mediaType: application/octet-stream
          headers:
            compressed:
              title: Data Compression
              type: boolean
              default: false
      default: json
  template:
    from:
      uri: "kamelet:source"
      steps:
        [...]
```

The dataTypes section may define message headers that the Kamelet produces. Also the section defines one to many supported data types for in/out/error. In the sample two data types are defined for the source Kamelet as an output (json and binary). Each data type specification is able to define a mediaType, additional dependencies, headers and a schema.

In a KameletBinding users may choose the output data type when referencing the Kamelet:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: event-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: event-source
      dataTypes:
        out: 
          format: binary
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: event-sink
```

The binding explicitly defines the output data type on the `event-source` Kamelet reference. The Kamelet source produces the output as `binary` accordingly.

Same applies for input data types where the Kamelet reference in a binding may choose from different supported input types of a Kamelet.

**Release Note**
```release-note
feat: Support data types in Kamelets
```

### CODE REVIEW

**Comment by manstis** [comment]
Completely unrelated to your PR @christophd but how did you re-generate [this](https://github.com/apache/camel-k/blob/880b993e51a6387e43c711f7febd63a73fbb99dd/pkg/apis/camel/v1alpha1/zz_generated.deepcopy.go)?

I couldn't get it to generate with `make generate` on my [PR](https://github.com/apache/camel-k/pull/4097).

**Comment by christophd** [comment]
@manstis I called

```
make clean
make generate
make build
make images
```

One of them did the trick for me 😅

**Comment by manstis** [comment]
> One of them did the trick for me

LOL.. None of them re-generated it for me.. oh well... the mystery deepens.

**Comment by squakez** [comment]
> 

`make generate` is the one in charge to refresh autogenerated code (which include deepcopies)

**Review by squakez — COMMENTED** [review]
Nice work, thanks! I have a couple of questions though:
1) What is be the default behavior when the data type is not selected?
2) Would it be possible to include some E2E test covering the new scenario? Ie, creating a Kamelet that has some customized data type.

**Comment by christophd** [comment]
@squakez thanks for the questions

> What is be the default behavior when the data type is not selected?

Each Kamelet has a default behavior. There is a `default` field in the dataTypes section for in/out/error and this should reflect the default behavior. Only when users define some data type in the binding additional logic will be applied.

> Would it be possible to include some E2E test covering the new scenario? Ie, creating a Kamelet that has some customized data type.

Yes, of course. Many Kamelets being used in the e2e tests already use the `dataTypes` section (they have been using the old `types` section and I refactored the Kamelets to use the new structure). For the KameletBinding adding some e2e tests regarding data types will be a future task when the actual implementation follows. This PR only adds the data type specifications to the CRDs. I am going to work on the implementation in the binding as soon as this has been accepted and merged

**Comment by squakez** [comment]
Okey, then, if I understand correctly, this PR only set the specification, but it would not yet be usable, waiting for the implementation in Kamelets/Camel code. Is that right?

**Comment by christophd** [comment]
@squakez yes, right adding data types information to a Kamelet is just informational for now. Using a data type in a KameletBinding does not have any affect at the moment.

**Comment by squakez** [comment]
Okey, then, IMO we can leave this on hold while the development is not ready. I don't like have things that have no real usage as they can confuse customers trying to use it. However the spec configuration will be good to go for me once the business logic will be implemented. I will mark this as WIP if it's okey for you.

**Review by squakez — APPROVED** [review]

**Comment by christophd** [comment]
Added the implementation of the data types support in KameletBindings.

The idea is to allow the user to specify the data types for output/input on Kamelet references in a binding (see source and sink Kamelets in example below).

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: event-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: event-source
    dataTypes:
      out:
        format: cloudevents
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: event-sink
    dataTypes:
      in:
        format: binary
```

Once the user explicitly defines the data types in the binding Camel K automatically adds respective steps (using the data-type-action Kamelet) in order to apply the data types for input/output (see generated `template-flow.yaml` below).

```yaml
from:
  uri: kamelet:event-source/source
  steps:
    - kamelet:
        name: data-type-action/source-out
    - kamelet:
        name: data-type-action/sink-in
    - to: kamelet:event-sink/sink
```

This is for data types being set on source and sink Kamelet references in a binding. Also, the user is able to add data types to Kamelet reference used in the steps section of a binding:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: event-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: event-source
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1alpha1
        name: log-action
      dataTypes:
        out:
          format: binary
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: event-sink
```

This time the generated `template-flow.yaml` looks like this:

```yaml
from:
  uri: kamelet:event-source/source
  steps:
    - pipeline:
        id: action-0-pipeline
        steps:
          - kamelet:
              name: log-action/action-0
          - kamelet:
              name: data-type-action/action-0-out
    - to: kamelet:event-sink/sink
```

Camel K uses a pipeline step in order to apply the data type action as an output of the log-action step.

The automatically added data type-action Kamelet steps will apply the given data format using the format name and an optional component scheme. At the moment the data type conversion logic is loaded from the camel-kamelet-utils library that holds some default data type implementations for AWS-S3, AWS-DDB and common String and binary data types (see https://github.com/apache/camel-kamelets/tree/main/library/camel-kamelets-utils/src/main/java/org/apache/camel/kamelets/utils/format/converter).

**Comment by christophd** [comment]
👀 @oscerd @lburgazzoli please have a look, too 🙏

**Comment by christophd** [comment]
FYI the YAKS tests failing because I need to release a new YAKS version supporting Kamelet data types first. This is being addressed in https://github.com/citrusframework/yaks/pull/469

**Review by squakez — APPROVED** [review]
Nice work. I think that once all those changes are ready we should consider if it makes sense to promote Kamelet API from `v1alpha1` to `v1`.

**Pull request merged**
