### PR TITLE
fix(#3800): Add proper kamel linux binary on MacOS

### PR DESCRIPTION
**Pull request by christophd**
Try to fix Makefile syntax

### CODE REVIEW

**Comment by christophd** [comment]
@oscerd sorry, I have screwed up the Makefile. Let's see if this is better and the CI jobs are happy

**Review by oscerd — APPROVED** [review]

**Comment by gansheer** [comment]
This fix definitely works better on Linux.

**Comment by christophd** [comment]
@gansheer yes, but now it is not working on MacOS anymore 😵 I have to investigate

**Comment by oscerd** [comment]
> @gansheer yes, but now it is not working on MacOS anymore dizzy_face I have to investigate

We could also revert and find a better solution. The fix was done only for MacOS.

**Comment by gansheer** [comment]
> > @gansheer yes, but now it is not working on MacOS anymore dizzy_face I have to investigate
> 
> We could also revert and find a better solution. The fix was done only for MacOS.

That seems to be a sensible approach since the main branch no longer build images on non MacOS Linux.

**Comment by christophd** [comment]
@oscerd @gansheer now I am sorted. I did not know that Makefile is so fuzzy about tabs vs. spaces

It should be fixed now (at least it is working on my MacOS again). Let's see what the CI jobs do report

**Comment by oscerd** [comment]
I think it's fine if we merge. This stuff is only for building, so no need to wait for common/install and knative.

**Comment by oscerd** [comment]
Thanks for the fast fix.

**Pull request merged**
