### PR TITLE
Kamel local inspect: In case of missing format, show the output in th…

### PR DESCRIPTION
**Pull request by oscerd**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by astefanutti** [comment]
It seems some changes to `.github/actions/backport` have sneaked in?

**Comment by oscerd** [comment]
Yes, there were some more commits in backport I guess. Let me try to clean up.

**Comment by oscerd** [comment]
@astefanutti fixed

**Review by astefanutti — APPROVED** [review]

**Comment by astefanutti** [comment]
Thanks!

**Comment by oscerd** [comment]
The failure doesn't seem related

**Pull request merged**
