### PR TITLE
[TEST] Add autoscaling test

### PR DESCRIPTION
**Pull request by bouskaJ**
backport https://github.com/apache/camel-k/pull/3322

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by squakez — APPROVED** [review]

**Comment by christophd** [comment]
@bouskaJ @squakez Heads up #3358 introduces some changes to the e2e tests. In particular the tests need to use unique operator ids when installing Camel K on the test namespaces. The same operator ids need to be used when running integrations.

Depending on what PR is merged 1st changes need to apply

**Comment by squakez** [comment]
Thanks @christophd - as this is a backport on a release branch, it should not be necessary

**Comment by christophd** [comment]
@squakez ah yes, just did a stupid copy & paste. thx

**Comment by squakez** [comment]
Failures are not related to this PR.

**Pull request merged**
