### PR TITLE
kind/feature/5395/expand pod template spec

### PR DESCRIPTION
**Pull request by hernanDatgDev**
Adding pod template support for field: AutomountServiceAccountToken

Closes https://github.com/apache/camel-k/issues/5395

**Release Note**
```release-note
feat: Adding pod template support for field: AutomountServiceAccountToken
```

### CODE REVIEW

**Comment by hernanDatgDev** [comment]
Hi, I'm not sure what value should actually be added for the "protobuf" string in pkg/apis/camel/v1/integration_types.go. The value I gave was `protobuf:"varint,8,opt,name=automountServiceAccountToken"` taking inspiration from other boolean values however the `8` is just a guess. What's an appropriate value to add when introducing new fields?

**Comment by claudio4j** [comment]
You can follow the k8s api [podspec](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3668) and set `21`

**Comment by hernanDatgDev** [comment]
@claudio4j Thanks I found the right values. Also I noticed in `pkg/apis/camel/v1/integration_types.go` it has some outdated make goal. To get the right functionality I ran `make generate` instead. Would it be appropriate to update this comment as well?
```
Run "make generate-deepcopy" to regenerate code after modifying this file
```

**Review by squakez — COMMENTED** [review]
This is where we definetely need at least a unit test to validate the feature. Have a look at https://github.com/apache/camel-k/blob/main/pkg/trait/pod_test.go and create at least one test that would add the new value and verify this is correctly added to the Deployment.

**Comment by squakez** [comment]
To consider if this is really ready to merge: https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/pod.20template.20fields.20interfere.20with.20knative

**Comment by hernanDatgDev** [comment]
I added the test to ensure that the field is set properly on the deployment. I also relayed with my security team and it we only need this field so that we can set it to false which does not interfere with Knative. It is only when this field is explicitly set to `True` that Knative interferes through validation. 
So for my team and this field specifically this PR would be enough. There are other fields that we'd like set however those do have issues with Knative so I'm working on getting conversations started with the Knative teams.

**Comment by claudio4j** [comment]
>  It is only when this field is explicitly set to True that Knative interferes through validation

**Review by claudio4j — APPROVED** [review]

**Review by squakez — APPROVED** [review]

**Pull request merged**
