### PR TITLE
feat(core): Support S2I for builder image generation

### PR DESCRIPTION
**Pull request by gansheer**
Ref #4297

## Motivation

Add S2I support for builder image generation for better support on Openshift.

## Description

* Add initialize builder image on catalog:
* creates (or replace) a BuildConfig resource
* creates (or replace) an ImageStream resource
* create a new builder image from dockerfile and source binary
* Light refactoring of S2I code

The `HOME` env variable has been added on builder image execution to some errors on file permissions without.

**Release Note**
```release-note
Add S2I support for builder image generation
```

### CODE REVIEW

**Comment by gansheer** [comment]
@lburgazzoli @astefanutti and anyone who have some knowledge on Openshift please don't hesitate to review, I would really some openshift feedback :smile:

**Review by squakez — COMMENTED** [review]
LGTM. There is some code duplication with the builder/s2i. As we want to release CK 2 ASAP, consider if you want to address in this PR or create a follow up issue not to left pending any tech debt unattended. Thanks!

**Review by oscerd — APPROVED** [review]

**Review by claudio4j — APPROVED** [review]

**Comment by squakez** [comment]
@gansheer please, let me know when it's ready to merge. If you're addressing the comments provided in the PR or we create follow up issues.

**Comment by gansheer** [comment]
> @gansheer please, let me know when it's ready to merge. If you're addressing the comments provided in the PR or we create follow up issues.

On my side it is ready to merge

I took care of some part of the refactoring, but for the more complex part of refactoring I would prefer we open a follow up issue when the olm tests are more reliable after the 1.12.1 release as it could be impacted by #4418.

**Comment by squakez** [comment]
Merged. Please, take care to log any relevant follow up issue.

**Pull request merged**
