### PR TITLE
chore: Update rbac authorization k8s from v1beta1 to v1

### PR DESCRIPTION
**Pull request by christophd**
**Release Note**
```release-note
Update Role-based Access Control from v1beta1 to v1
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by astefanutti — COMMENTED** [review]
Could you run `make build-resources` to update the embedded resources?

**Comment by christophd** [comment]
@astefanutti good one, thx - done

**Review by astefanutti — APPROVED** [review]
Was planning to do it anytime soon, thanks a lot!

**Review by nicolaferraro — APPROVED** [review]

**Comment by astefanutti** [comment]
Thanks!

**Pull request merged**
