### PR TITLE
chore(build): upgrade to go1.17

### PR DESCRIPTION
**Pull request by chenrui333**
**Release Note**
```release-note
Upgrade Go to version 1.17
```
relates to #2579

### CODE REVIEW

**Comment by chenrui333** [comment]
not stale yet

**Comment by astefanutti** [comment]
> @astefanutti any objection on moving forward to 1.17 for next Camel K minor version? We can resolve the conflicts of this PR and merge it.

@squakez no objection, assuming the k8s and Knative versions Camel K currently depend on are compatible.

**Comment by squakez** [comment]
@chenrui333 do you mind rebasing with the latest from `main`? if tests pass then we're ready to go.

**Comment by squakez** [comment]
@tadayosi are you already working to rebase this one? Please let me know, otherwise I'll take care.

**Comment by tadayosi** [comment]
@squakez I haven't done anything yet. So please go ahead. Thank you!

**Comment by squakez** [comment]
I have rebased these changes, but I cannot push back because the original fork no longer exists. I noticed that however this PR did not update the `go.mod` to require `go 1.17`. When updating to that value, the build starts to fail because there are more things that we need to take in consideration, in particular with generated clients. I am trying to sort all the issues out and see if we can move to 1.17.

**Comment by squakez** [comment]
I'm trying to rebase but the original fork was deleted. I am cherry picking the commit and opening a new PR.

**Pull request closed without merging**
