### PR TITLE
feat/coverage report workflow

### PR DESCRIPTION
**Pull request by realMartinez**
- added a workflow which comments on newly created or updated PRs the change to code coverage those PRs made.
- the messages can be customized depending on whether the code coverage was changed positively, negatively or was unchanged.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by realMartinez** [comment]
Not at all, as long as it is supported by markdown it should be fine

**Review by gansheer — APPROVED** [review]

**Comment by realMartinez** [comment]
I changed the format, now messages should look like this, for positive code coverage I used the checkmark.

:camel: **Thank You for contributing!** :camel: 

 **Code Coverage Report** :warning:
 - Coverage changed from: **39.2%** -> **39.0%**
 - Coverage difference: **-0.2%**

**Review by claudio4j — APPROVED** [review]

**Comment by squakez** [comment]
Great stuff. Question, why the coverage action is failing? It seems it fails with a 403, maybe some permission issue? also, I guess that this very same PR should have the new bot comment.

**Review by squakez — APPROVED** [review]

**Comment by realMartinez** [comment]
Yeah I looked into it and it seems to be a permission issue

**Pull request merged**
