### PR TITLE
fix(e2e): Fix E2E test using kamelet my-own-timer-source

### PR DESCRIPTION
**Pull request by gansheer**
ref #4750

## Description 

Remove duplicate usage of "my-own-timer-source" kamelet.

**Release Note**
```release-note
fix(e2e): Fix E2E test using kamelet my-own-timer-source
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by gansheer** [comment]
> LGTM. It's a best practice to use a different resource name. The problem is likely to be fixed, but the root cause probably will be there.

I agree, I could not find quickly the root cause. It could be some parallel test execution issue as the common tests run on a preinstalled operator.

**Comment by squakez** [comment]
It seems the change is breaking some other e2e test, is it that?

**Comment by gansheer** [comment]
> It seems the change is breaking some other e2e test, is it that?

Unfortunately no, the one still in error was already failing before. I will comment the code for now and add a comment in the current issue. As it is, it is not something a documented behavior. I will keep it commented in case the fact the failure become the signal we have another issues with kamelets.

**Comment by gansheer** [comment]
@squakez I think the refactoring fixed the issue. I am firing the CI to ensure the other failures were from an external source.

**Comment by squakez** [comment]
> @squakez I think the refactoring fixed the issue. I am firing the CI to ensure the other failures were from an external source.

Okey. However, there's no need to force push just for re-running checks. Please ping any committer to just re-run the failing one in order to shorten the feedback cycle.

**Pull request merged**
