### PR TITLE
Platform choice for aarch64 is incorrect

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by tdiesler** [comment]
Failing in 

* TestKameletFromCustomRepository 
* TestSyntheticIntegrationFromDeployment

### TestKameletFromCustomRepository

```
dump.go:337:     > {"level":"info","ts":"2024-04-02T09:07:08Z","logger":"camel-k.controller.integration","msg":"State transition","request-namespace":"test-4c80bbc4-66ca-46d8-a4a2-130225b98668","request-name":"timer-custom-kamelet-integration","api-version":"camel.apache.org/v1","kind":"Integration","ns":"test-4c80bbc4-66ca-46d8-a4a2-130225b98668","name":"timer-custom-kamelet-integration","phase-from":"Initialization","phase-to":"Error"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T09:07:08Z","logger":"camel-k.controller.integration","msg":"Integration error","request-namespace":"test-4c80bbc4-66ca-46d8-a4a2-130225b98668","request-name":"timer-custom-kamelet-integration","api-version":"camel.apache.org/v1","kind":"Integration","ns":"test-4c80bbc4-66ca-46d8-a4a2-130225b98668","name":"timer-custom-kamelet-integration","reason":"InitializationFailed","error-message":"error during trait customization: kamelets trait execution failed: Get \"[https://api.github.com/repos/squakez/ck-kamelet-test-repo/contents/kamelets\](https://api.github.com/repos/squakez/ck-kamelet-test-repo/contents/kamelets/)": dial tcp 140.82.112.6:443: i/o timeout"}
      dump.go:337:     > {"level":"error","ts":"2024-04-02T09:07:08Z","msg":"Reconciler error","controller":"integration-controller","controllerGroup":"camel.apache.org","controllerKind":"Integration","Integration":{"name":"timer-custom-kamelet-integration","namespace":"test-4c80bbc4-66ca-46d8-a4a2-130225b98668"},"namespace":"test-4c80bbc4-66ca-46d8-a4a2-130225b98668","name":"timer-custom-kamelet-integration","reconcileID":"49f96865-f3a1-49dc-aed1-4daebe64a364","error":"error during trait customization: kamelets trait execution failed: Get \"[https://api.github.com/repos/squakez/ck-kamelet-test-repo/contents/kamelets\](https://api.github.com/repos/squakez/ck-kamelet-test-repo/contents/kamelets/)": dial tcp 140.82.112.6:443: i/o timeout","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:265
```

### TestSyntheticIntegrationFromDeployment

```
dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:10Z","logger":"camel-k.controller.integration","msg":"First readiness after 20s","request-namespace":"default","request-name":"timer-source","ready-after":20,"api-version":"","kind":"","ns":"default","name":"timer-source"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:21Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:21Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:22Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:22Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:22Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:24Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:25Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:25Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:25Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:25Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:26Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:26Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:337:     > {"level":"info","ts":"2024-04-02T08:58:27Z","logger":"camel-k.controller.integration","msg":"Ignoring request because resource is not assigned to current operator","request-namespace":"test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3","request-name":"my-it"}
      dump.go:286: Ignoring pod java-764d69b7bc-7bv2r
      dump.go:286: Ignoring pod timer-source-684d8f748b-v7nx5
      dump.go:286: Ignoring pod yaml-847d9c6b65-9vj2c
      dump.go:307: -------------------- end dumping namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3 --------------------
      test_support.go:2870: Clean up test namespace: test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  2024-04-02T08:59:27Z	DEBUG	camel-k	Finding available platforms in namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  2024-04-02T08:59:27Z	DEBUG	camel-k	Found active integration platform camel-k-synthetic-env
  Camel K Integration Platform removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Integration Profile removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Config Maps removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Registry Secret removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Platform Kamelets removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Platform Camel Catalogs removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Operator removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Role Bindings removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Role Bindings removed from namespace kube-public
  Camel K Roles removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
  Camel K Service Accounts removed from namespace test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
      test_support.go:2876: Successfully cleaned up test namespace: test-345fddcb-c51d-4a3a-b615-3edd6aeb94d3
```

**Comment by tdiesler** [comment]
@squakez Can we please run this?

**Comment by squakez** [comment]
@tdiesler is this good to merge?

**Review by squakez — APPROVED** [review]

**Comment by tdiesler** [comment]
Yes, pls merge

**Pull request merged**
