### PR TITLE
feat(cli): Allow to specify custom Kaniko and Buildah images

### LINKED ISSUE #3350: Parametrize kaniko executor image to point to private registry
HI Team,

Can some please help in knowing how can I override following hardcoded image URL "gcr.io/kaniko-project/executor" to point to my private registry where we have this image already uploaded?

I see that it is currently hardcoded in "**pkg/controller/build/build_pod.go**" 

```
spec:
  affinity: {}
  containers:
  - args:
    - --dockerfile=Dockerfile
    - --context=/builder/kit-caidqd64odbspdoahn5g/context
    - --destination=840203264751.dkr.ecr.us-west-2.amazonaws.com/default/camel-k-kit-caidqd64odbspdoahn5g:1057558
    - --cache=false
    - --cache-dir=/kaniko/cache
    image: **gcr.io/kaniko-project/executor:v0.17.1**
    imagePullPolicy: IfNotPresent
    name: kaniko
```

Will really appreciate quick guidance here. Thanks!

### PR DESCRIPTION
**Pull request by essobedo**
fixes #3350 

## Motivation

The docker images to use for Kaniko and Buildah are hard coded and should be configurable

## Modifications:

* Add cli new parameters to provide the custom docker images (`kaniko-executor-image`, `kaniko-warmer-image`, and `buildah-image`)
* Convert the default docker images into constants

**Release Note**
```release-note
Additional parameters have been added to specify custom Kaniko and Buildah images which are respectively 
`kaniko-executor-image`, `kaniko-warmer-image`, and `buildah-image`
```

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by tadayosi** [comment]
Buildah and Kaniko CI tests keep failing. Let's make sure it passes them before merging this pull req.

**Review by tadayosi — CHANGES_REQUESTED** [review]
Builder tests keep failing.

**Comment by essobedo** [comment]
@tadayosi yes it is failing for an unknown reason. I don't know if it is related but the command `make generate-deepcopy` has no effect, any idea why?

**Comment by tadayosi** [comment]
Probably you should run `make generate` and update the CRDs.

**Comment by tadayosi** [comment]
You'd also need to run `make` after generating CRDs to update `pkg/resources/resources.go`.

**Comment by essobedo** [comment]
> Probably you should run `make generate` and update the CRDs.

FYI the command `make generate` fails on Mac OS (12.5.1) in ./script/gen_crd.sh with an error of type:
```
./script/gen_crd.sh
sed: 1: "/creationTimestamp:/a\  ...": extra characters after \ at the end of a command
make: *** [generate] Error 1
```

**Comment by essobedo** [comment]
The command `make generate-deepcopy` has still no effect

**Comment by tadayosi** [comment]
@essobedo Please see:
https://camel.apache.org/camel-k/next/contributing/developers.html#requirements
We ask macOS users to use gnu-sed instead.

**Comment by essobedo** [comment]
> @essobedo Please see: https://camel.apache.org/camel-k/next/contributing/developers.html#requirements We ask macOS users to use gnu-sed instead.

Thx for sharing, I installed gnu-sed already but my path was actually incorrect, it works well now, thx again 🙏

**Comment by essobedo** [comment]
Tests are failing because it cannot find Camel K Runtime 1.14.0

**Comment by essobedo** [comment]
The only test that fails is `TestNativeIntegrations/automatic_rollout_deployment_from_fast-jar_to_native_kit` which is a known failing test.

**Review by tadayosi — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
