### PR TITLE
fix(builder): strenghten matching dependencies heuristic

### PR DESCRIPTION
**Pull request by squakez**
The `TestRunBuildOrderStrategyMatchingDependencies` uses to be flaky. I've investigated and the root cause seems to be the heuristic we are using to detect matching dependencies. The following piece of code `missing >= len(required)/2` seem to be the problem, in the sense that when the number of `required` is odd, then, the code is rounded to a integer value that is not matching the condition. The ideal solution is to add +1 to that division, or removing the equality which would sort the same effect.

This PR address the problem. The heuristic used is strengthen against this corner case and validated with a few unit test.

**Release Note**
```release-note
fix(builder): strenghten matching dependencies heuristic
```

### CODE REVIEW

**Comment by squakez** [comment]
Part of #5090 - FYI @lburgazzoli

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@squakez can you add some better release notes ? it is not clear to me what is the motivation of this change and how it differs form the current behavior

**Comment by squakez** [comment]
> @squakez can you add some better release notes ? it is not clear to me what is the motivation of this change and how it differs form the current behavior and what would be the impact.

Sure. Done. Thanks.

**Review by lburgazzoli — APPROVED** [review]

**Review by christophd — APPROVED** [review]
Good work. Thanks!

**Review by gansheer — APPROVED** [review]

**Pull request merged**
