### PR TITLE
Fix some OLM tests recently broken

### PR DESCRIPTION
**Pull request by gansheer**
Revert "feat(core): Fix Operator and Builder Pod user as non root 1000"

This reverts commit 8272026321f79a8bedfdacf357c806210338888c.

The user 0 (root) is set on:
* Dockerfile's folders that the operatory copy 
* SecurityContext.FSGroup of the operator's pod

**Release Note**
```release-note
Revert usage of non-root user (1000) on operator and builder pods FS.
```

### CODE REVIEW

**Review by squakez — APPROVED** [review]
I guess you mean these checks:
✅ TestOLMInstallation (5m49.82s)
✅ TestOLMInstallation/run_smoke_test_ephemeral (2m42.8s)
✅ TestOLMInstallation/run_smoke_test_pvc (14.72s)

Yeah, that is the problem of assuming some checks are failing. I'm working to solve the upgrade problem (as soon as we release 1.12.1 it will be fixed), so we can trust 100% our tests.

**Comment by squakez** [comment]
It seems this one has fixed those failing validation. Can I merge!?

**Comment by gansheer** [comment]
It depends if you are in a hurry to fix these 3 tests, because this revert will break this PR #4417 on S2I builder.  Else I will work some more to have both the fixes and the S2I builder working in this PR.

**Comment by squakez** [comment]
> It depends if you are in a hurry to fix these 3 tests, because this revert will break this PR #4417 on S2I builder. Else I will work some more to have both the fixes and the S2I builder working in this PR.

Ah, okey, I did not get that part. No hurry, feel free to go ahead with a solid solution then.

**Comment by gansheer** [comment]
@squakez 
My last commits where working, so I did some squashing on them. This version is good on the olm tests and the S2I builder. I will probably make some more modifications on permissions later when I can actually test the olm mode locally.

**Comment by squakez** [comment]
> @squakez My last commits where working, so I did some squashing on them. This version is good on the olm tests and the S2I builder. I will probably make some more modifications on permissions later when I can actually test the olm mode locally.

Thanks for taking care. I'll merge as soon as the checks are green then.

**Pull request merged**
