### PR TITLE
fix(ci): settings directory

### PR DESCRIPTION
**Pull request by squakez**
Enabling native as a nightly test to run separately from the release wf.

Ref #4035 

**Release Note**
```release-note
fix(ci): settings directory
```

### CODE REVIEW

**Comment by squakez** [comment]
cc @essobedo I wonder if this is going to simplify the feature you're enabling.

**Comment by essobedo** [comment]
This cannot pass on an ubuntu runner once https://github.com/apache/camel-k/pull/4021 will be merged due to a lack RAM

**Comment by squakez** [comment]
fyi @essobedo , this should remove the native and fix the failure we were experiencing on the setting.

**Review by essobedo — APPROVED** [review]

**Comment by squakez** [comment]
Skipping checks, not required.

**Pull request merged**
