### PR TITLE
Copy feature for copying the command

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Copy feature for copying the command

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Hi, thanks for the PR. How does it work? Is it rendered on Github only or also in the Antora website? https://camel.apache.org/camel-k/latest/

**Comment by NiteshKoushik** [comment]
Hello,
In the same page it would give a Copy option to cope the code which is present in the respected section. When I was reading the document I felt if there was a copy feature to copy the code it would help.
I have done similar contribution for different open source document on GitHub, which helped most of them to copy the code on single click, I was trying the same.

**Comment by NiteshKoushik** [comment]
Hello,
In the same page it would give a Copy option to copy the code which is present in the respected section. When I was reading the document I felt if there was a copy feature to copy the code it would help.
I have done similar contribution for different open source document on GitHub, which helped most of them to copy the code on single click, I was trying the same.

**Comment by NiteshKoushik** [comment]
Thanks for the comments and suggestion. 
But there should be a way to implement this feature, so that it helps the document readers.

**Comment by NiteshKoushik** [comment]
I can close this PR. If this wont work.

**Comment by oscerd** [comment]
> Thanks for the comments and suggestion.
> But there should be a way to implement this feature, so that it helps the document readers.

As far as I know to render this to antora is not feasible. Isn't it @zregvart ?

**Comment by zregvart** [comment]
For this we would need an [asciidoc extension](https://docs.antora.org/antora/2.2/playbook/configure-asciidoc/#extensions) developed and submitted to the [camel-website repository](https://github.com/apache/camel-website/blob/5251f7f46d834f8305e745f9dbf8ad1b4c8559fe/site.yml#L32-L34), we already have [two examples](https://github.com/apache/camel-website/tree/master/extensions) of extensions there.

**Comment by NiteshKoushik** [comment]
Hello,
I see multiple PR has opened for the same request (copy feature) from Antora and Asciidoctor.

https://gitlab.com/antora/antora-ui-default/issues/70
https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/61

And the source code which they have shared is a valid. Need to wait whether it will included in Antora or not.

Thanks

**Pull request closed without merging**
