### PR TITLE
[test] Detect camel quarkus version dynamically in monitoring test

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Review by astefanutti — APPROVED** [review]
Very nice!

Should we remove the comment: https://github.com/apache/camel-k/blob/cad0ed357087514bca2fef95cb97913da96981ce/e2e/yaks/openshift/monitoring/app/pom.xml#L29

**Comment by llowinge** [comment]
@astefanutti Yes, i will remove it. Btw. should i even remove the whole line 
`<version.camel.quarkus>1.0.0-CR2</version.camel.quarkus>` ? It would be more safe so we will test with the correct version. But i will leave decision up to you.

**Comment by astefanutti** [comment]
@llowinge right, let's remove the `version.camel.quarkus` default.

**Review by oscerd — APPROVED** [review]

**Comment by astefanutti** [comment]
Thanks!

**Pull request merged**
