### PR TITLE
Normalize the Spectrum log messages

### PR DESCRIPTION
**Pull request by orpiske**
Fixes GH issue #2276

**Release Note**
```release-note
Normalize Spectrum build messages
```

### CODE REVIEW

**Comment by orpiske** [comment]
I am working on the test case for this. It took me a while to get Kind running locally.

**Comment by orpiske** [comment]
@astefanutti I think we'll have to leave the integration test for a separate PR. We have other log messages that are non-structured. They are not printed by our code directly, instead they are printed by dependencies (i.e.: leader election from k8s is one of the offending code). So we'll have to review those before introducing a test for this. 

If you are OK with that, my suggestion is to go as it is and I'll open another issue for myself related to the remaining non-structured bits. 

wdyt?

**Comment by astefanutti** [comment]
@orpiske thanks a lot for the update!

Indeed, structured logging is still in alpha in Kubernetes 1.19:
https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/. It's also not really clear how to activate structured logging in `client-go` (which hosts the leader election code that `controller-runtime` calls), maybe `klog.SetLogger()` can be used?

I agree with your suggestion to merge this, and create a follow up issue. In addition to fixing the Spectrum case, this PR has also helped identifying the remaining bits 👍🏼.

**Comment by orpiske** [comment]
> @orpiske thanks a lot for the update!
> 
> Indeed, structured logging is still in alpha in Kubernetes 1.19:
> https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/. It's also not really clear how to activate structured logging in `client-go` (which hosts the leader election code that `controller-runtime` calls), maybe `klog.SetLogger()` can be used?
> 
> I agree with your suggestion to merge this, and create a follow up issue. In addition to fixing the Spectrum case, this PR has also helped identifying the remaining bits 👍🏼.

Thanks! I opened #2286 and I will explore that one next.

**Pull request merged**
