### PR TITLE
[fix] Use bigger timeout to start querying metrics in test

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Comment by llowinge** [comment]
@astefanutti

**Review by astefanutti — APPROVED** [review]

**Comment by astefanutti** [comment]
Hum, it seems the GitHub action has deleted the CHANGELOG.md file.

**Comment by oscerd** [comment]
> Hum, it seems the GitHub action has deleted the CHANGELOG.md file.

It should be because the changelog should be generated only on master branch, there was a PR from @christophd yesterday

**Comment by astefanutti** [comment]
@oscerd yes, I find it surprising that the file got deleted.

@llowinge would you mind force push your branch to override the second commit?

**Comment by llowinge** [comment]
@astefanutti Done, thank you.

**Pull request merged**
