### PR TITLE
[ENTESB-15644] Fix monitoring test

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Comment by llowinge** [comment]
@astefanutti Do you think it could be backported to M4 or M5 branches ?

**Review by astefanutti — APPROVED** [review]
Thanks!

**Comment by astefanutti** [comment]
> @astefanutti Do you think it could be backported to M4 or M5 branches ?

@llowinge could you create a PR to `release-1.3.x` branch?

**Comment by llowinge** [comment]
> > @astefanutti Do you think it could be backported to M4 or M5 branches ?
> 
> @llowinge could you create a PR to `release-1.3.x` branch?

Yes, i will.

**Pull request merged**
