### PR TITLE
Updated reference link in the quarkus.adoc

### PR DESCRIPTION
**Pull request by nshendye**
Updated reference link in the quarkus.adoc. 

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This needs to be a relative url. Otherwise the website build will fail.

**Comment by oscerd** [comment]
This cam be closed

**Comment by nshendye** [comment]
> This needs to be a relative url. Otherwise the website build will fail.
@oscerd 
The syntax for the url in current doc results in the error when publishing the downstream documentation. We single source the upstream traits pages. That's why I updated the link. Any thoughts on how to fix this?

**Comment by oscerd** [comment]
The only solution I see for you it is to substitute the relative url on your side.

**Pull request closed without merging**
