### PR TITLE
fix make generate-crd error

### LINKED ISSUE #3453: `make generate-crd` error
Ref [gnu-sed failing](https://github.com/apache/camel-k/pull/3427#issuecomment-1182903367)

gnu-sed is failing, causing the post processing steps to abort returning an error like:

```
go: creating new go.mod: module tmp
CONTROLLER_GEN=/Users/chikki/go/bin/controller-gen ./script/gen_crd.sh
sed: 1: "/creationTimestamp:/a\\ ...": extra characters after \ at the end of a command
make: *** [generate-crd] Error 1
```

System: Mac OSX

Probable reason: BSD/macOS sed requires an actual newline character to follow `a\`, before the text to append

### PR DESCRIPTION
**Pull request by SubhasmitaSw**
kind/bug 
fixes #3453 

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by astefanutti — APPROVED** [review]

**Comment by christophd** [comment]
As this seems to be related to BSD/macOS sed and Camel K has stopped to support this please consider installing gnu-sed on your machine (see also #3372 and #3398).

**Review by tadayosi — CHANGES_REQUESTED** [review]
`verify-generate` fails because this patch doesn't work on Linux.

And as @christophd says you can install `brew install gnu-sed` on macOS instead. Otherwise we'd need to have linux/mac switch everywhere in the build scripts.

**Comment by SubhasmitaSw** [comment]
@christophd @tadayosi I already have gnu-sed installed in my system still there was this error and it got resolved if I changed to this

**Comment by tadayosi** [comment]
@SubhasmitaSw What's the output of the following command?
```
$ sed --version
```

**Comment by SubhasmitaSw** [comment]
@tadayosi 
`sed --version` gives: 

```
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
	sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

`strings $(which sed)` gives: 

```
@(#)PROGRAM:sed  PROJECT:text_cmds-138.100.3
33333Ca@
$FreeBSD$
$FreeBSD$
$FreeBSD$
$FreeBSD$
malloc
%lu: %s: unexpected EOF (pending }'s)
0123456789/\$
%lu: %s: command expected
%lu: %s: invalid command code %c
%lu: %s: command %c expects up to %d address(es), found %d
%lu: %s: unexpected }
%lu: %s: extra characters at the end of %c command
%lu: %s: command %c expects \ followed by text
%lu: %s: extra characters after \ at the end of %c command
%lu: %s: filename expected
w command
read command
branch
label
%lu: %s: empty label
%lu: %s: substitute pattern can not be delimited by newline or backslash
%lu: %s: unterminated substitute pattern
%lu: %s: extra text at the end of a transform command
%lu: %s: unterminated regular expression
%lu: %s: expected context address
realloc
%lu: %s: whitespace after %s
%lu: %s: duplicate label '%s'
%lu: %s: \ can not be used as a string delimiter
%lu: %s: newline can not be used as a string delimiter
%lu: %s: unbalanced brackets ([])
%lu: %s: RE error: %s
%lu: %s: \%c not defined in the RE
%lu: %s: unescaped newline inside substitute pattern
%lu: %s: unterminated substitute in regular expression
%lu: %s: more than one number or 'g' in substitute flags
%lu: %s: overflow in the 'N' substitute flag
wfile too long
%lu: %s: no wfile specified
%lu: %s: bad flag in substitute command: '%c'
%lu: %s: transform pattern can not be delimited by newline or backslash
%lu: %s: unterminated transform source string
%lu: %s: unterminated transform target string
%lu: %s: transform strings are not the same length
%lu: %s: undefined label '%s'
%lu: %s: unused label '%s'
EI:ae:f:i:lnru
setting line buffered output failed
setting unbuffered output failed
stdout
stdin
"%s"
 ..."
-I or -i may not be used with stdin
rename()
fclose()
%s: %s %s
in-place editing only
works for regular files
%s: name too long
strdup
%s/.!%ld!%s
usage: %s script [-Ealnru] [-i extension] [file ...]
%s [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
first RE may not be empty
RE error: %s
%lu: %s: \%u not defined in the RE
%s: %s
COLUMNS
\abfrtv
\%03o
```

**Comment by tadayosi** [comment]
@SubhasmitaSw That means you are still using the builtin BSD sed. Make sure to run:
```
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```
and put the same line to your `.bashrc` or `.bash_profile`.

**Comment by SubhasmitaSw** [comment]
> @SubhasmitaSw That means you are still using the builtin BSD sed. Make sure to run:
> 
> ```
> export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
> ```
> 
> and put the same line to your `.bashrc` or `.bash_profile`.

I've tried all of this, I'm not able to counter the problem.

**Comment by tadayosi** [comment]
@SubhasmitaSw What's the output of the command now?
```
type -a sed
```
Also does `sed --version` output `sed (GNU sed) x.x` now?

**Comment by SubhasmitaSw** [comment]
@tadayosi 
Output of `type -a sed` 
```
sed is /usr/bin/sed
```
Output of `sed --version` 
```
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
	sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by tadayosi** [comment]
@SubhasmitaSw Then you are still using BSD sed. Please use GNU sed.

**Comment by tadayosi** [comment]
Assuming it's already answered, let's go ahead and close it. Please feel free to ask me if the issue is not yet resolved.

**Pull request closed without merging**
