### PR TITLE
chore(lint): run golanci-lint on travis

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Why travis is so slow recently? I don't think it's due to the changes in the e2e tests, it even does not start sometimes...

**Comment by nicolaferraro** [comment]
I see this in the log:

```
$ ./golangci-lint run
ERRO Running error: context loading failed: failed to load program with go/packages: go [list -f {{context.GOARCH}} {{context.Compiler}} -- unsafe]: exit status 1: go: github.com/inconshreveable/mousetrap@v1.0.0: git init --bare in /home/travis/gopath/pkg/mod/cache/vcs/789073dcfc473e7775315ee47ed8dda0b5d23fc69eec98221905dcf98b9d5848: exit status 128:
	fatal: cannot copy '/usr/share/git-core/templates/hooks/pre-commit.sample' to '/home/travis/gopath/pkg/mod/cache/vcs/789073dcfc473e7775315ee47ed8dda0b5d23fc69eec98221905dcf98b9d5848/hooks/pre-commit.sample': File exists
```

Maybe we should not continue with integration tests if lint fails.

**Comment by lburgazzoli** [comment]
it should do it by default :)

**Comment by nicolaferraro** [comment]
Maybe not ;)

https://medium.com/@manjula.cse/how-to-stop-the-execution-of-travis-pipeline-if-script-exits-with-an-error-f0e5a43206bf

**Comment by nicolaferraro** [comment]
Why this works on Travis?? ;)

**Pull request merged**
