### PR TITLE
[fix] Use in-place editing

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by llowinge** [comment]
@astefanutti

**Review by astefanutti — APPROVED** [review]

**Comment by astefanutti** [comment]
@llowinge it looks good to me. Some tests are failing but it guess it's not related to this PR as monitoring test suite does not run upstream IIRC?

**Comment by llowinge** [comment]
@astefanutti Exactly.

**Comment by astefanutti** [comment]
Merging as test failures are unrelated.

**Pull request merged**
