### PR TITLE
chore(e2e) Add options to customize vars with ENVs in cli e2e tests

### PR DESCRIPTION
**Pull request by mmajerni**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by squakez — APPROVED** [review]

**Comment by squakez** [comment]
Backport to `main` as well if this is a general fix. Thanks!

**Comment by squakez** [comment]
```
❌ TestSyntheticIntegrationFromDeployment (1m21.39s)
      synthetic_test.go:123: 
          Timed out after 60.000s.
          Expected
              <v1.ConditionStatus>: False
          to equal
              <v1.ConditionStatus>: True
```
This one was failing. I've restarted the check but it does not look to be a flaky one, if you want to give a look while the second check attempt is running.

**Comment by mmajerni** [comment]
TestSyntheticIntegrationFromDeployment is located in subfolder `advanced` and the change is made in `cli` subfolder so other tests except these in CLI folder should not be affected.

**Comment by squakez** [comment]
> TestSyntheticIntegrationFromDeployment is located in subfolder `advanced` and the change is made in `cli` subfolder so other tests except these in CLI folder should not be affected.

True. I see the second attempt cleared. You can disregard such a comment, thanks.

**Pull request merged**
