### PR TITLE
Fix #2236: Add Service Binding E2E test

### LINKED ISSUE #2236: Create E2E test for Service Binding Operator

### PR DESCRIPTION
**Pull request by johnpoth**
Fixes #2236, thanks !

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by nicolaferraro** [comment]
It's great to have this in the test suite, I'm just not sure if it's the right approach. Maybe @bouskaJ can help to check what's the best way.

For testing service binding, I was thinking to something like:
- We add this test to a specific dir in the e2e folder (without the SB installation part)
- We install service-binding in some of the clusters where we run e2e tests
- We run the test specifically only in those clusters

Having the cluster-wide installation as part of the test run may cause issues. Wdyt @bouskaJ?

**Comment by bouskaJ** [comment]
I agree with @nicolaferraro. I would prefer to install the `service-binding` in the GitHub action workflow as we already do for OLM in   https://github.com/apache/camel-k/blob/main/.github/workflows/upgrade.yml#L95-L100

**Comment by johnpoth** [comment]
Sounds good, updated, thanks !

**Comment by astefanutti** [comment]
@johnpoth do you think it'd be worth having a real backing service, that the test Integration would be bound to, and assert the Camel route can actual connect to this backing service?

**Comment by johnpoth** [comment]
@astefanutti agreed, removed the OpenShift until we upgrade to OCP 4...

As for the test, adoption of Service Binding is (last time I checked) quite limited in terms of back services often requiring manually editing CRDs and doesn't work out of the box... this is just a smoke test until adoption increases

**Comment by astefanutti** [comment]
@johnpoth sounds good, that's a good start, that can be improved any time ServiceBinding operator becomes more widespread.

**Pull request merged**
