### PR TITLE
chore(ci): 1.8.1 release post actions

### PR DESCRIPTION
**Pull request by astefanutti**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Sorry completely forgot about this. Silly me

**Comment by astefanutti** [comment]
> Sorry completely forgot about this. Silly me

No worries, that's everybody's job :)

**Comment by astefanutti** [comment]
Blocked by #3064.

**Comment by astefanutti** [comment]
Let me try merging this and see if that fixes some the issues from #3064.

**Pull request merged**
