### PR TITLE
refactored redundant kamel kit flags

### PR DESCRIPTION
**Pull request by Gre8t**
Removed redundant flags from the kit command. The functionality of these flags which are configmaps, properties and secrets already appears in the trait flag

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by Gre8t** [comment]
@astefanutti

**Review by squakez — CHANGES_REQUESTED** [review]
The goal of this issue is not just removing those parameters. Instead we need to keep using them, but, delegating the logic to the related trait. As an example, you can see what we do in the `run` subcommand, where we parse and convert certain parameters to the related trait: https://github.com/apache/camel-k/blob/main/pkg/cmd/run.go#L555

**Review by squakez — APPROVED** [review]
It looks good. Last thing is to use some tool to format the code (ie `gofmt`).

**Review by squakez — APPROVED** [review]

**Comment by squakez** [comment]
Thanks!

**Comment by Gre8t** [comment]
@squakez I should be the one saying thanks.

**Comment by squakez** [comment]
> @squakez I should be the one saying thanks.

Glad to help. We really value your contributions!

**Comment by Gre8t** [comment]
You are welcome. 
I'm Loving this community already.

**Pull request merged**
