### PR TITLE
Remove overinstalling the timer kamelet

### PR DESCRIPTION
**Pull request by bouskaJ**
port https://github.com/apache/camel-k/pull/3496

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by tadayosi — COMMENTED** [review]
Seems knative test CI starts to fail with this. Is this really a correct fix?

**Comment by bouskaJ** [comment]
> Seems knative test CI starts to fail with this. Is this really a correct fix?

You are right. It seems that the operator has a problem finding kamelet with global installation. Now it should be OK.

**Comment by tadayosi** [comment]
Rebase this please

**Comment by tadayosi** [comment]
All failures are known ones as per https://github.com/apache/camel-k/issues/3560. Let's merge it.

**Pull request merged**
