### PR TITLE
Split tests by language

### PR DESCRIPTION
**Pull request by bouskaJ**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by nicolaferraro — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by bouskaJ** [comment]
It seems that `go test -timeout 60m -v ./e2e/common/... -tags=integration` does not print it's output in progress but it prits everything at the end of the test execution.

Travis CI seems to have an issue with it:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

Should I change the command to `go test -timeout 60m -v ./e2e/common -tags=integration && go test -timeout 60m -v ./e2e/common/languages -tags=integration`? What do you thing about it?

**Comment by bouskaJ** [comment]
@nicolaferraro WDYT?

**Comment by nicolaferraro** [comment]
> @nicolaferraro WDYT?

I was thinking about this but did not have time to look carefully.
I remember there was an issue in travis that happened when an execution did not produce any output for a long time. But don't know why this change triggers that issue.

This may be something completely silly, but I remember some issue about the `...` notation here: https://github.com/apache/camel-k/pull/1822/files#diff-9aecbcc15d64c3e7a146ee5776a35e65b45fb72461e370c4e295dd90f6d45262R151

I remember a bug about that and maybe the go version in Travis is hitting that. Do you mind trying to run tests on explicit dirs or hack with versions?

**Comment by bouskaJ** [comment]
> > @nicolaferraro WDYT?
> 
> I was thinking about this but did not have time to look carefully.
> I remember there was an issue in travis that happened when an execution did not produce any output for a long time. But don't know why this change triggers that issue.
> 
> This may be something completely silly, but I remember some issue about the `...` notation here: https://github.com/apache/camel-k/pull/1822/files#diff-9aecbcc15d64c3e7a146ee5776a35e65b45fb72461e370c4e295dd90f6d45262R151
> 
> I remember a bug about that and maybe the go version in Travis is hitting that. Do you mind trying to run tests on explicit dirs or hack with versions?

I hope this could help https://github.com/apache/camel-k/pull/1822/files#diff-b2c08647d24f7df76cd7a5f2adc119ab93451ad2f662ded422e55943fd889b04R86

**Comment by bouskaJ** [comment]
Damn! The https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received is not working in the script that runs the integration test (https://travis-ci.com/github/apache/camel-k/builds/204584739). Then I would go with ` go test -timeout 60m -v ./e2e/common -tags=integration && go test -timeout 60m -v ./e2e/common/languages -tags=integration`.

**Comment by bouskaJ** [comment]
@nicolaferraro I am done. Can you recheck/merge this PR?

**Review by nicolaferraro — APPROVED** [review]

**Comment by nicolaferraro** [comment]
Thanks

**Pull request merged**
