### PR TITLE
chore: Upgrade golang.org/x/net

### PR DESCRIPTION
**Pull request by gansheer**
Fix the security check: https://github.com/apache/camel-k/actions/runs/8553670220/job/23437323789

**Release Note**
```release-note
chore: Upgrade golang.org/x/net
```

### CODE REVIEW

**Comment by squakez** [comment]
I think this should be naturally solved when the GH action are updating the golang version to 1.21.9 which is fixing that problem as well.

**Review by squakez — APPROVED** [review]
I amend my previous review. You're right. This is affecting also the net library which does not belong to golang codebase.

**Comment by squakez** [comment]
This requires backporting to `release-2.3.x`. Can you please take care @gansheer?

**Comment by gansheer** [comment]
> This requires backporting to `release-2.3.x`. Can you please take care @gansheer?

On it.

**Pull request merged**
