### PR TITLE
Updated camel-k-runtime version to the latest snapshot

### PR DESCRIPTION
**Pull request by orpiske**
Folks, I am raising this PR to align the current main branch w/ the
development branch of the camel-k-runtime. This a pre work required to
bring support for the resume API to Camel K. 

Please don't merge it yet - let's discuss it first

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
@squakez @oscerd Guys, any thoughts about when it would be appropriate to bump the camel k runtime on this?

**Comment by oscerd** [comment]
We usually bump when we have a staging release

**Comment by orpiske** [comment]
> We usually bump when we have a staging release

Aha, thanks! So, I guess it can wait until we release that. Thanks for the heads up.

**Comment by oscerd** [comment]
It should be superseded by #3561

**Comment by orpiske** [comment]
> We're moving the runtime to 1.14.0 in #3561 is this still a valid PR or will be supersede by that one?

That's great news. We can close this one.

**Pull request closed without merging**
