### PR TITLE
[TEST] Global kamelet test - support for openshift

### PR DESCRIPTION
**Pull request by asmigala**
Make global kamelet test work on openshift. Took the same approach as #2653

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by bouskaJ** [comment]
@squakez @astefanutti @oscerd can you merge it?

**Comment by oscerd** [comment]
No, we are releasing 1.8.0 at this time and the tests are all failing

**Comment by bouskaJ** [comment]
It seems that the failed tests are not caused by this PR.
```
./script/build_catalog.sh 1.10.0-SNAPSHOT -Dcatalog.file=camel-catalog-1.10.0-SNAPSHOT.yaml -Dcatalog.runtime=quarkus -Dstaging.repo=""
Error:  Plugin org.apache.camel.k:camel-k-maven-plugin:1.10.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.apache.camel.k:camel-k-maven-plugin:jar:1.10.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/content/repositories/snapshots/) -> [Help 1]
```
 Can you rerun the CI?

**Review by oscerd — APPROVED** [review]

**Comment by bouskaJ** [comment]
@astefanutti The CI is fixed. Can you rerun it?

**Comment by bouskaJ** [comment]
Maybe @asmigala will need to rebase it.

**Comment by astefanutti** [comment]
@bouskaJ thanks, yes I think that needs a rebase 👍🏼.

**Comment by asmigala** [comment]
@astefanutti rebased

**Comment by bouskaJ** [comment]
@astefanutti the CI is finally green :tada: can you merge it?

**Comment by astefanutti** [comment]
@bouskaJ it has landed, thanks!

**Pull request merged**
