### PR TITLE
Related to #1190: add more logs when patch fails

### LINKED ISSUE #1190: Invalid JSON Patch error when running simple Camel-K example with 1.0.0-RC1
Just wanted to give the latest Camel-K release 1.0.0-RC1 a try. Installation went OK. Camel-K itself is running. I then issue the simple command `kamel run hello.groovy`.

After some time the started build-kit pod will end up in an _Init:Error_ state. Reason seems to be that the *builder* init container stops and exits with an error. The last line in the logs of the init container ist the following:

```json
{"level":"error","ts":1578825389.8346853,"logger":"camel-k.builder","msg":"","error":"Invalid JSON Patch","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/apache/camel-k/pkg/util/log.Logger.Error\n\tgithub.com/apache/camel-k@/pkg/util/log/log.go:74\ngithub.com/apache/camel-k/pkg/cmd/builder.exitOnError\n\tgithub.com/apache/camel-k@/pkg/cmd/builder/builder.go:105\ngithub.com/apache/camel-k/pkg/cmd/builder.Run\n\tgithub.com/apache/camel-k@/pkg/cmd/builder/builder.go:91\ngithub.com/apache/camel-k/pkg/cmd.(*builderCmdOptions).run\n\tgithub.com/apache/camel-k@/pkg/cmd/builder.go:51\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tgithub.com/apache/camel-k@/cmd/kamel/main.go:46\nruntime.main\n\truntime/proc.go:203"}
```

I am running everything locally on a Mac using Docker Desktop with Kubernetes enabled:
- Engine: 19.03.5
- Kubernetes: v1.14.8

### PR DESCRIPTION
**Pull request by nicolaferraro**
Fix #1190

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by nicolaferraro** [comment]
It seems the CI error that's happening constantly is due to this specific problem.. logs should tell something this time..

**Comment by astefanutti** [comment]
Yes it's very possible the patch creation is still a bit fragile, especially in edge / error cases.

**Comment by nicolaferraro** [comment]
> Yes it's very possible the patch creation is still a bit fragile, especially in edge / error cases.

Forgot the log was json in this case, but it's clear that the patch is empty:
```
{"level":"error","ts":1582287788.2336826,"logger":"camel-k.builder","msg":"\n--- patch ---\n\n-------------\n","error":"Invalid JSON Patch","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/apache/camel-k/pkg/util/log.Logger.Error\n\tgithub.com/apache/camel-k@/pkg/util/log/log.go:74\ngithub.com/apache/camel-k/pkg/cmd/builder.exitOnError\n\tgithub.com/apache/camel-k@/pkg/cmd/builder/builder.go:108\ngithub.com/apache/camel-k/pkg/cmd/builder.Run\n\tgithub.com/apache/camel-k@/pkg/cmd/builder/builder.go:91\ngithub.com/apache/camel-k/pkg/cmd.(*builderCmdOptions).run\n\tgithub.com/apache/camel-k@/pkg/cmd/builder.go:51\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tgithub.com/apache/camel-k@/cmd/kamel/main.go:46\nruntime.main\n\truntime/proc.go:203"}
```

Should we just skip the patch in this case or it is a signal of some other error @astefanutti ?

**Comment by astefanutti** [comment]
Generally patching should be skipped when the patch is empty, I'm just surprised the build output leads to an empty patch, which means the build status hasn't changed after the build has run.

**Comment by nicolaferraro** [comment]
> Generally patching should be skipped when the patch is empty, I'm just surprised the build output leads to an empty patch, which means the build status hasn't changed after the build has run.

I'm not sure why it's doing another build to be honest.. a yaml integration has been already run previously and they look similar:

*first one*
```
- from:
    uri: "timer:yaml"
    parameters:
      period: "5s"
    steps:
      - set-header:
          name: "m"
          constant: "string!"
      - set-body:
          simple: "Magic${header.m}"
      - to: "log:info"

```

*second:*
```
- from:
    uri: "timer:yaml"
    parameters:
      period: "1s"
    steps:
      - set-body:
          constant: "Hello Camel K from yaml"
      - to: "log:info"

```

**Comment by nicolaferraro** [comment]
Seems to fix.. I'm merging to rebase other PRs

**Pull request merged**
