### PR TITLE
feat(trait): Migrate prometheus trait from microprofile metrics to micrometer

### LINKED ISSUE #1773: Default to using Micrometer for integration monitoring
Quarkus recommends using Micrometer over MicroProfile Metrics starting Quarkus version 1.9:

https://quarkus.io/blog/micrometer-metrics/

The Prometheus trait should default to using Micrometer instead of MP metrics with Quarkus.

This requires the Camel Quarkus Micrometer extension to be available.

### PR DESCRIPTION
**Pull request by gansheer**
Fixes #1773 

## Motivation

In Quarkus 3 / Camel 4, microprofile-metrics will be removed, and micrometer extension is its replacement.
The prometheus trait need to be modified to use the micrometer extension.

## Description

The micrometer extension replaces the microprofile extension, with the additional prometheus registry.
The e2e existing test is updated to be the most similar as possible in terms of metrics tested, but since micrometer offers less possibilities there are some adaptations.

**Release Note**
```release-note
Migrate prometheus trait from microprofile metrics to micrometer
```

### CODE REVIEW

**Comment by gansheer** [comment]
The PR is in draft until I manage to fix the e2e test.

**Review by squakez — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by gansheer** [comment]
I am trying to see if it is possible to add in the prometheus trait code the addition of a builder property `quarkus.micrometer.export.json.enabled=true` to ensure json api is available by default. I haven't manage to. Is there a way to do it while acting on the `e *Environment` object ?

**Comment by squakez** [comment]
I think this is another case where we need to understand how to implement a trait leaving implementation details about runtime outside of Camel K: https://github.com/apache/camel-k/issues/4166

**Comment by gansheer** [comment]
> I think this is another case where we need to understand how to implement a trait leaving implementation details about runtime outside of Camel K: #4166

I see, I will exclude it from this issue and document it in the documentation's example for now.

**Comment by squakez** [comment]
Thanks!

**Pull request merged**
