### PR TITLE
[1.10.x] fix: reconciliation loops behaviors

### LINKED ISSUE #3980: Failure when mounting condifgmap and secrets with the same name
If you try to configure camel-k to mount resources with the same name, as example:

```yaml
metadata:
    annotations:
        trait.camel.apache.org/mount.configs: [ "configmap:foo", "secret:foo" ]
```

Then the operator would fail as the generated deployment would become invalid (two volumes with the same name) and the integration would be stuck forever. In such case, the integration should enter the error phase and the failure must be reported to the readiness condition at some point.

### PR DESCRIPTION
**Pull request by squakez**
Closes #3980 

**Release Note**
```release-note
fix: reconciliation loops behaviors
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by tadayosi — APPROVED** [review]

**Comment by oscerd** [comment]
When this is merged I'll start a new release

**Comment by squakez** [comment]
> When this is merged I'll start a new release

There is some failure I'm trying to understand on the release branch related to this change. Hopefully I'll sort it out shortly.

**Comment by oscerd** [comment]
Ok, just ping me when I could start

**Comment by squakez** [comment]
@oscerd @lburgazzoli unfortunately this backport is not as easy as I thought. We had worked quite a lot in version 1.11 on the controller logic before this fix, so it seems we should bring in quite a lot to have a fully functional version. Not sure at this stage how to proceed.

**Comment by squakez** [comment]
I may have a working solution (cherry picking from cherry pick...). Closing this and opening a new PR shortly.

**Pull request closed without merging**
