### PR TITLE
fix typos on resources.adoc and improve language

### PR DESCRIPTION
**Pull request by mertdotcc**
Fix a couple of typos and improve the overall language in the Advanced->Resource Management documentation

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by mertdotcc** [comment]
@oscerd What's the build/publish process like for the Camel-K documentation page? I don't see the changes in this merged commit reflected in the website yet.

**Comment by oscerd** [comment]
It needs to be done manually from the CI.

**Comment by mertdotcc** [comment]
The changes are still not reflected in the actual Camel K website. Pardon me if this is a silly question, but who updates the website? What do you exactly mean by "it needs to be done manually from the CI"? Is it something I can do? Thanks!

**Comment by oscerd** [comment]
The last good build of the website was on 10 March. This one was merged on 12. That's the reason. It seems there are troubles with the build now: https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/1166/console

We need to investigate

**Comment by mertdotcc** [comment]
It seems that there were some successful builds on the 24th and 21st of March, but I still don't see the fix reflected on the [docs](https://camel.apache.org/camel-k/1.12.x/installation/advanced/resources.html). What needs to be done exactly?

**Comment by oscerd** [comment]
It should be published already. That's weird at least

**Comment by oscerd** [comment]
I'll check on Monday

**Comment by oscerd** [comment]
https://camel.apache.org/camel-k/next/installation/advanced/resources.html

This is because you were looking at 1.12.x branch and not on main. Your changes are showed only on the next release. You should backport the change on release-1.12.x and older doc branches.

**Comment by mertdotcc** [comment]
Alright, that makes sense. 👍🏻 

As per backporting my changes to 1.12.x and older branches, that is something I haven't done before. Could you please provide some instructions? 

Thanks.

**Comment by oscerd** [comment]
The active branches are release-1.12.x, release-1.11.x and release-1.10.x.

Copy the commit id of the PR merge on main and on the branches listed above run

git cherry-pick '-S' <commit_id> 

if it works straightforward, open a PR, otherwise you'll need to manually modify the doc files on the branches.

**Pull request merged**
