### PR TITLE
Initial architecture documentation

### PR DESCRIPTION
**Pull request by lburgazzoli**
This PR provides some initial docs about the camel-k archiecture I've
extracted from some of the presentaiton I've done.

I'll provide some more content in the coming days.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by oscerd** [comment]
I just want to stress this is documentation done by @lburgazzoli, world is really near his end.

**Comment by astefanutti** [comment]
> I just want to stress this is documentation done by @lburgazzoli, world is really near his end.

There are even diagrams included, so that is going to be apocalyptic!

**Comment by astefanutti** [comment]
I'm pretty sure @lburgazzoli used the [GPT-3 API](https://openai.com/blog/openai-api/) to generate the doc instead of writing it 😄!

**Comment by lburgazzoli** [comment]
> I'm pretty sure @lburgazzoli used the [GPT-3 API](https://openai.com/blog/openai-api/) to generate the doc instead of writing it smile!

na, done it the hard way ... I did want to know how complex it is to write documentation :P

**Comment by lburgazzoli** [comment]
looks like travis [succeeded](https://travis-ci.org/github/apache/camel-k/builds/710004602) but failed to report the status here

**Pull request merged**
