### PR TITLE
[WIP] chore: remove deprecated code in pre 1.6 releases

### PR DESCRIPTION
**Pull request by christophd**
Closes https://github.com/apache/camel-k/issues/2751

**Release Note**
```release-note
chore: remove deprecated code in pre 1.6 releases
```

### CODE REVIEW

**Comment by squakez** [comment]
Watch out, I think you were working on a dirty tree ;)

**Comment by christophd** [comment]
@squakez I see the tests now running so the YAKS installation issue has been solved. There is still a common problem with the tests applying Kamelets and bindings via `kubectl apply` in pre test scripts.

I see `Cannot reconcile Integration source-sink: error during trait customization: kamelet "timer-source" is not Ready: Error` for instance. Seems like there is something wrong in the camel-k operator.

**Comment by squakez** [comment]
Thanks. I will have a further look now that the tests are running fine. Keep this one open as we may use for further experiments.

**Comment by squakez** [comment]
Will be fixed in #2932 we can close this draft, thanks!

**Pull request closed without merging**
