### PR TITLE
fix(e2e): stabilise TestNativeBinding (1.10.x)

### PR DESCRIPTION
**Pull request by tadayosi**
Backport #3747

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I'll try to include this in 1.10.2

**Review by squakez — APPROVED** [review]

**Comment by oscerd** [comment]
Release 1.10.2 has been cut, this will go in 1.10.3.

**Comment by tadayosi** [comment]
@oscerd Yes, it's not in a hurry. I'll see if I can improve this a bit more before merging it.

**Comment by tadayosi** [comment]
It looks like something is going wrong with Knative serving.
```
      dump.go:268:     > {"level":"info","ts":1666186902.059175,"logger":"camel-k","msg":"could not find any knative type in namespace test-99c98bf6-e772-43c3-aa13-db4d840f77a5, last error was: services.serving.knative.dev is forbidden: User \"system:serviceaccount:test-99c98bf6-e772-43c3-aa13-db4d840f77a5:camel-k-operator\" cannot list resource \"services\" in API group \"serving.knative.dev\" in the namespace \"test-99c98bf6-e772-43c3-aa13-db4d840f77a5\""}
```

**Comment by tadayosi** [comment]
> It looks like something is going wrong with Knative serving.
> 
> > dump.go:268:     > {"level":"info","ts":1666186902.059175,"logger":"camel-k","msg":"could not find any knative type in namespace test-99c98bf6-e772-43c3-aa13-db4d840f77a5, last error was: services.serving.knative.dev is forbidden: User "system:serviceaccount:test-99c98bf6-e772-43c3-aa13-db4d840f77a5:camel-k-operator" cannot list resource "services" in API group "serving.knative.dev" in the namespace "test-99c98bf6-e772-43c3-aa13-db4d840f77a5""}

OK, this doesn't seem to be an issue: #2397

**Comment by tadayosi** [comment]
The `native-it` tests keep failing, but let's try to address them with another pull req. I'm merging this one.

**Pull request merged**
