### PR TITLE
test: Missing cli e2e tests implementation

### PR DESCRIPTION
**Pull request by vsokolov00**
PR for: 
https://issues.redhat.com/browse/FUSEQE-13290
https://issues.redhat.com/browse/FUSEQE-13294

### CODE REVIEW

**Comment by squakez** [comment]
I think the test spotted an hidden issue:
```
=== RUN   TestKamelCLIBind/bind_timer_to_log
KameletBinding.camel.apache.org "test-timer-source-to-log" is invalid: []: Invalid value: map[string]interface {}{"kind":"KameletBinding", "apiVersion":"camel.apache.org/v1alpha1", "metadata":map[string]interface {}{"uid":"2948e0fe-e2f1-11eb-b545-000d3a02688e", "selfLink":"", "clusterName":"", "name":"test-timer-source-to-log", "namespace":"test-6a95d672-8ac8-4df7-8688-1eacb6220973", "creationTimestamp":"2021-07-12T09:11:37Z", "generation":1}, "spec":map[string]interface {}{"source":map[string]interface {}{"ref":map[string]interface {}{"kind":"Kamelet", "namespace":"test-6a95d672-8ac8-4df7-8688-1eacb6220973", "name":"test-timer-source", "apiVersion":"camel.apache.org/v1alpha1"}, "properties":map[string]interface {}{"message":"helloTest"}}, "sink":map[string]interface {}{"uri":"log:info"}, "errorHandler":interface {}(nil)}}: validation failure list:
spec.errorHandler in body must be of type object: "null"
```
Probably the `bind` operation is setting a `null` error handler, when instead it should be omitted as empty.

**Comment by squakez** [comment]
Should be rebased after #2496 is merged.

**Comment by squakez** [comment]
Please @vsokolov00, rebase this PR to see if now the test pass correctly.

**Comment by vsokolov00** [comment]
@squakez pr is ready to merge! :)

**Review by squakez — APPROVED** [review]

**Comment by astefanutti** [comment]
@vsokolov00 could you please run `go fmt` over the modified files?

**Comment by vsokolov00** [comment]
```cli git:(missing-cli-e2e-tests) ✗ go fmt bind_test.go 
     cli git:(missing-cli-e2e-tests) ✗ go fmt log_test.go
     support git:(missing-cli-e2e-tests) ✗ go fmt test_support.go```
Empty output @astefanutti

**Comment by astefanutti** [comment]
@vsokolov00 when I run for example `go fmt ./e2e/support` locally I get:

```go
func GetOutputStringAsync(cmd *cobra.Command) func() string {
	var buffer bytes.Buffer
	stdout := bufio.NewWriter(&buffer)

	cmd.SetOut(stdout)
	go cmd.Execute()

	return func() string {
		return buffer.String()
	}
}
```

compared to:

```go
func GetOutputStringAsync(cmd *cobra.Command) func () string {
	var buffer bytes.Buffer
	stdout := bufio.NewWriter(&buffer)

	cmd.SetOut(stdout)
	go cmd.Execute()

	return func () string{
		return buffer.String()
	}
}
```

I think `go fmt` takes packages as input rather than individual files.

**Comment by vsokolov00** [comment]
strange that even when I run this command over the package it return nothing.. But thanks to your comment I spotted the problem, thanks! @astefanutti

**Comment by vsokolov00** [comment]
You are right, it should be executed over the whole packages (also it automatically edits problem code) @astefanutti

**Review by astefanutti — APPROVED** [review]

**Pull request merged**
