### PR TITLE
chore: Make scripts portable

### PR DESCRIPTION
**Pull request by christophd**
Use portable sed command options -E instead of -r and explicitly add empty extension as -i option (required for MacOs)

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by astefanutti — APPROVED** [review]
Very cool!

**Comment by astefanutti** [comment]
Seems like there are some conflicts.

**Comment by christophd** [comment]
@astefanutti I do not see any conflicts. Tests are failing on that PR though. But is this a general issue as I see other PRs failing on those tests, too?

**Comment by astefanutti** [comment]
@christophd I see the message "This branch cannot be rebased due to conflicts".

You're right, the tests failure is not related to this PR and should hopefully be fixed with #1724.

**Comment by christophd** [comment]
Closing in favor of a new PR that has no rebase conflicts

**Pull request closed without merging**
