### PR TITLE
Rebase camel-main

### PR DESCRIPTION
**Pull request by orpiske**
There was some conflicts on `pkg/controller/kameletbinding/common.go` and I suggest we review it carefully. 

To resolve the conflict, I prioritized the changes on camel-main instead of the changes on main, but we can do it the other way around.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
@nicolaferraro @lburgazzoli the conflict seems to be related to refactoring changes that both of you did, therefore I am marking you both as reviewers ... as it seemed to me both changes were valid.

**Comment by orpiske** [comment]
c/c: @oscerd @astefanutti @squakez

**Comment by oscerd** [comment]
Thanks @orpiske

**Comment by lburgazzoli** [comment]
LGTM

**Comment by orpiske** [comment]
This one is broken. I am back to it now.

**Comment by orpiske** [comment]
Fixed. Had to merge `common.go` manually

**Pull request merged**
