### PR TITLE
Fix: TestCreateCatalog fail when runtime is 3.6.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by claudio4j**
Fix https://github.com/apache/camel-k/issues/5099

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by squakez — CHANGES_REQUESTED** [review]
Sorry, but this is not good. We cannot hardcode variables. We need the dynamic value there which will be generated against the default catalog. If you change this, it will fail later when we bump the catalog to the next version. Maybe what we need is to regen the defaults when we run the build with a different catalog. Ideally we must execute `make build` (which include `test` phase) in order to do the regen.

**Comment by claudio4j** [comment]
> We cannot hardcode variables. 

This is a test only, for the catalog to be created in the IntegrationPlatform and the status to be "Ready", it would really not matter the version, since the "mvn camel-k-maven-plugin:generate-catalog" is to output the catalog yaml file. The catalog generation is also covered in camel-k-maven-plugin project.

The real problem with this particular test is the snapshot version, the apache snapshot repository is not set. I can change the test to include the snapshot repo and retain the defaults.

**Comment by squakez** [comment]
FYI, this seems to be a regression. It was working 2 days ago: https://github.com/apache/camel-k/actions/runs/7634756816/job/20799121558#step:4:929

**Comment by squakez** [comment]
The root cause is that the new catalog has a wrong `quarkus-version`:
```
    metadata:
      camel-quarkus.version: 3.6.0
      camel.version: 4.2.0
      jib.layer-filter-extension-maven.version: 0.3.0
      jib.maven-plugin.version: 3.4.0
      quarkus.native-builder-image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
      quarkus.version: 3.6.0
```

**Comment by claudio4j** [comment]
That version is defined in https://github.com/apache/camel-k-runtime/blob/main/pom.xml#L46
Can you run: `make DEFAULT_RUNTIME_VERSION=3.6.0-SNAPSHOT clean build`

**Comment by claudio4j** [comment]
The [nightly test failed](https://github.com/apache/camel-k/actions/runs/7649141367/job/20843059854#step:4:1008) exactly in the same spot.
The problem is the missing snapshot maven repo.
I think it would not be a problem to hard code the LTS version in the test code and in the nightly, add the snapshot repository. I will change the code to accommodate this behavior.

**Comment by squakez** [comment]
IMO the problem is in the last runtime change. I'd be more inclined to revert the latest changes there instead. At least you can confirm that one is the root cause or this issue persist.

**Comment by claudio4j** [comment]
I see there is no [camel-k-runtime 3.6.0-SNAPHOST artifacts in apache repo](https://repository.apache.org/content/repositories/snapshots-group/org/apache/camel/k/camel-k-catalog/3.6.0-SNAPSHOT/).

Also several past nightly tests fails because of the same error: ` Could not find artifact org.apache.camel.k:camel-k-catalog:yaml:catalog:3.6.0-SNAPSHOT in apache-snapshots (https://repository.apache.org/content/repositories/snapshots-group)`.

Camel-k-runtime doesn't have a nightly build from main branch. From [this issue](https://github.com/apache/camel-k-runtime/issues/910), there is a snapshot release from a commit. Probably the snapshot apache repo prune some old snapshot artifacts.

I will close this PR, because the nightly checks should already check it camel-k with camel-k-runtime snapshot release.

**Pull request closed without merging**
