### PR TITLE
chore(olm): bump framework operator sdk from v1.16.0 to v1.26.1

### LINKED ISSUE #4105: Upgrade Operator Framework SDK version
The last released version of the operator framework SDK  is v1.26.1 : https://github.com/operator-framework/operator-sdk/releases/tag/v1.26.1.

The one we are using in the make scripts is :
https://github.com/apache/camel-k/blob/8056c0096dad112e95b7282f580c5a0a6801a1ed/script/Makefile#L31

Even if the script does not download this version if a newer one is already installed on the environment, we should probably upgrade considering the v1.16 was released in january 2022 https://github.com/operator-framework/operator-sdk/releases/tag/v1.16.0.

Is there a reason not to upgrade it ? What would be the impact of such an upgrade ?

### PR DESCRIPTION
**Pull request by gansheer**
Fixes #4105

**Release Note**
```release-note
Bump framework operator sdk from v1.16.0 to v1.26.1
```

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I guess this will affect also the prepare-operators script, I suppose

**Review by oscerd — APPROVED** [review]
Looks good btw

**Comment by gansheer** [comment]
I made some test on the bundle generated (in local build)  between 1.16 and 1.26.1 and I get this result:
```
diff -r bundle/Dockerfile bundle_1.26/Dockerfile
10c10
< LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.15.0+git
---
> LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.26.1
diff -r bundle/manifests/camel-k.clusterserviceversion.yaml bundle_1.26/manifests/camel-k.clusterserviceversion.yaml
197c197
<     createdAt: "2023-03-06T16:21:10Z"
---
>     createdAt: "2023-03-06T16:19:27Z"
200c200
<     operators.operatorframework.io/builder: operator-sdk-v1.15.0+git
---
>     operators.operatorframework.io/builder: operator-sdk-v1.26.1
329c329,336
<       - name: camel-k-operator
---
>       - label:
>           app: camel-k
>           app.kubernetes.io/component: operator
>           app.kubernetes.io/name: camel-k
>           app.kubernetes.io/version: 2.0.0-SNAPSHOT
>           camel.apache.org/component: operator
>           name: camel-k-operator
>         name: camel-k-operator
diff -r bundle/metadata/annotations.yaml bundle_1.26/metadata/annotations.yaml
9c9
<   operators.operatorframework.io.metrics.builder: operator-sdk-v1.15.0+git
---
>   operators.operatorframework.io.metrics.builder: operator-sdk-v1.26.1
```

Is there something that should cause some concern in this result for you @oscerd ?

**Comment by oscerd** [comment]
> I made some test on the bundle generated (in local build) between 1.16 and 1.26.1 and I get this result:
> 
> ```
> diff -r bundle/ bundle_1.26/
> diff -r bundle/Dockerfile bundle_1.26/Dockerfile
> 10c10
> < LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.15.0+git
> ---
> > LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.26.1
> diff -r bundle/manifests/camel-k.clusterserviceversion.yaml bundle_1.26/manifests/camel-k.clusterserviceversion.yaml
> 197c197
> <     createdAt: "2023-03-06T16:21:10Z"
> ---
> >     createdAt: "2023-03-06T16:19:27Z"
> 200c200
> <     operators.operatorframework.io/builder: operator-sdk-v1.15.0+git
> ---
> >     operators.operatorframework.io/builder: operator-sdk-v1.26.1
> 329c329,336
> <       - name: camel-k-operator
> ---
> >       - label:
> >           app: camel-k
> >           app.kubernetes.io/component: operator
> >           app.kubernetes.io/name: camel-k
> >           app.kubernetes.io/version: 2.0.0-SNAPSHOT
> >           camel.apache.org/component: operator
> >           name: camel-k-operator
> >         name: camel-k-operator
> diff -r bundle/metadata/annotations.yaml bundle_1.26/metadata/annotations.yaml
> 9c9
> <   operators.operatorframework.io.metrics.builder: operator-sdk-v1.15.0+git
> ---
> >   operators.operatorframework.io.metrics.builder: operator-sdk-v1.26.1
> ```
> 
> Is there something that should cause some concern in this result from your experience @oscerd ?

Nothing looks weird, we'll need to check once we create PR in operator hub and community prod for Openshift. The truth will be when they will test through their pipelines.

**Review by squakez — APPROVED** [review]

**Comment by squakez** [comment]
@gansheer the diff looks okey, no major changes in the bundle, so I don't think there won't be any problem. Let's wait the checks I've re-executed just to make sure there is no problem, in particular in the OLM suite.

**Comment by squakez** [comment]
@gansheer all looks good. Waiting your ok to merge this.

**Comment by gansheer** [comment]
@squakez LGTM too. Since no other concern has been raised I guess it's ready for merge :+1: .

**Pull request merged**
