### PR TITLE
Enhance Http proxy test about the OLM

### PR DESCRIPTION
**Pull request by bouskaJ**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by bouskaJ** [comment]
@astefanutti can you take a look at this? WDYT?

**Comment by astefanutti** [comment]
@bouskaJ I think that's a very good idea 👍🏼.

**Review by astefanutti — APPROVED** [review]

**Comment by bouskaJ** [comment]
@astefanutti do you know what's wrong with the `upgrade` test? Can you rerun/merge this?

```
Run ./.github/actions/kamel-build-bundle/build-index-image.sh \
time="2022-02-07T14:26:10Z" level=warning msg="--skip-tls flag is set: this mode is insecure and meant for development purposes only."
time="2022-02-07T14:26:10Z" level=info msg="building the index" bundles="[kind-registry:5000/apache/camel-k-bundle:1.9.0-SNAPSHOT]"
time="2022-02-07T14:26:10Z" level=info msg="Pulling previous image quay.io/operatorhubio/catalog:latest to get metadata" bundles="[kind-registry:5000/apache/camel-k-bundle:1.9.0-SNAPSHOT]"
time="2022-02-07T14:26:10Z" level=info msg="running /usr/bin/docker pull quay.io/operatorhubio/catalog:latest" bundles="[kind-registry:5000/apache/camel-k-bundle:1.9.0-SNAPSHOT]"
time="2022-02-07T14:26:14Z" level=info msg="running /usr/bin/docker pull quay.io/operatorhubio/catalog:latest" bundles="[kind-registry:5000/apache/camel-k-bundle:1.9.0-SNAPSHOT]"
time="2022-02-07T14:26:14Z" level=info msg="Getting label data from previous image" bundles="[kind-registry:5000/apache/camel-k-bundle:1.9.0-SNAPSHOT]"
time="2022-02-07T14:26:14Z" level=info msg="running docker inspect" bundles="[kind-registry:5000/apache/camel-k-bundle:1.9.0-SNAPSHOT]"
Error: index image quay.io/operatorhubio/catalog:latest missing label operators.operatorframework.io.index.database.v1
Usage:
  opm index add [flags]

Examples:

```

**Comment by astefanutti** [comment]
@bouskaJ please see #2972 for more details about the current OLM upgrade tests failure.

**Comment by bouskaJ** [comment]
@astefanutti @squakez all pipelines (except those two failing regularly ATM) passed. Can you merge?

**Pull request merged**
