### PR TITLE
Removed the deprecated --logging-level option (issue #2000)

### PR DESCRIPTION
**Pull request by orpiske**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
We'll need to rebase camel-main on main at some point.

**Review by astefanutti — APPROVED** [review]
I love reviewing "delete only" PR 😉!

**Comment by orpiske** [comment]
> We'll need to rebase camel-main on main at some point.

+1. I think we need to do it this week to not get too far behind on camel-main

**Comment by oscerd** [comment]
> > We'll need to rebase camel-main on main at some point.
> 
> +1. I think we need to do it this week to not get too far behind on camel-main

Yeah, here and on camel-k-runtime

**Review by squakez — COMMENTED** [review]
Nice cleaning work. I think we should include some documentation though in order to let the people know how to use/edit the logging trait. If we have it missing at all, we should take the opportunity and add a little entry (maybe under running/log menu section) explaining how to do that.

**Comment by orpiske** [comment]
> Nice cleaning work. I think we should include some documentation though in order to let the people know how to use/edit the logging trait. If we have it missing at all, we should take the opportunity and add a little entry (maybe under running/log menu section) explaining how to do that.

Thanks. We actually have the `logging.trait` documented within the traits: https://camel.apache.org/camel-k/latest/traits/logging.html. 

Maybe we should make it more easily accessible in the home page?

**Comment by astefanutti** [comment]
> > Nice cleaning work. I think we should include some documentation though in order to let the people know how to use/edit the logging trait. If we have it missing at all, we should take the opportunity and add a little entry (maybe under running/log menu section) explaining how to do that.
> 
> Thanks. We actually have the `logging.trait` documented within the traits: https://camel.apache.org/camel-k/latest/traits/logging.html.
> 
> Maybe we should make it more easily accessible in the home page?

I'd suggest to create a "Logging" page, under the "Observability" one, along with the existing monitoring documentation: https://camel.apache.org/camel-k/latest/observability/monitoring.html. At least that was the original intent of the "Observability" section, grouping Logging, Monitoring, and Tracing.

**Comment by squakez** [comment]
Yeah, I think we should have a dedicated section that will link to the log trait page as well. I'd say a short entry under /running/log would be enough for now.

**Comment by orpiske** [comment]
@astefanutti @squakez Thanks. Let me add the documentation as part of this PR before we merge this. 

I'm also wondering if we should include some simpler/smaller version of this as well: https://camel.apache.org/blog/2021/05/new-camel-k-logging-features/. 

If you have any suggestions, please let me know :)

**Comment by squakez** [comment]
> @astefanutti @squakez Thanks. Let me add the documentation as part of this PR before we merge this.
> 
> I'm also wondering if we should include some simpler/smaller version of this as well: https://camel.apache.org/blog/2021/05/new-camel-k-logging-features/.
> 
> If you have any suggestions, please let me know :)

Thanks @orpiske, I think a short version with basic info should be okey. From there you can add a link to the trait page where we explain more in details all those aspects.

**Comment by astefanutti** [comment]
@orpiske the content from https://camel.apache.org/blog/2021/05/new-camel-k-logging-features/ is would be exactly what's needed. I'd suggest to mimic the existing organisation for monitoring documentation, that is two pages, Operator and Integration, within Observability > Logging. Also a link from the `Running` page to the Integration logging could be good as suggested by @squakez.

**Comment by orpiske** [comment]
Added a bit of documentation.

**Review by astefanutti — APPROVED** [review]

**Comment by astefanutti** [comment]
Awesome, thanks @orpiske!

**Review by squakez — APPROVED** [review]
:+1:

**Pull request merged**
