### PR TITLE
JSon Logging Extension for Maven 3 and Maven 4

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@claudio4j @squakez  this Pr aims to make the process to enable maven jaon logging easier so instead of having to do some maven calsspath enrichment, we only need add the extension to the pom 

would be nice if you'd have a look

**Review by squakez — COMMENTED** [review]
I haven't worked on it lately, but I guess this change has to be coupled with the way how we create the operator container in https://github.com/apache/camel-k/blob/main/build/Dockerfile. @claudio4j may provide more inputs on this part as he has been working on it lately.

**Comment by claudio4j** [comment]
- the maven 3 module uses an older logstash and slf4j version, I suppose this is because of the slf4j 1.x version already in maven 3
- how this is this supposed to work to actually build an integration in camel-k-operator ?
- can we exclude maven4 module as maven4 is still in alpha and there is no plan yet to use maven4 in camel-k. This can help code maintenance.

**Comment by lburgazzoli** [comment]
> how this is this supposed to work to actually build an integration in camel-k-operator

The operator should either configure the extension on the generated project or define it in the global maven' settings.xml

**Pull request closed without merging**
