### PR TITLE
fix(trait): service binding

### PR DESCRIPTION
**Pull request by squakez**
**Release Note**
```release-note
fix(trait): service binding
```

### CODE REVIEW

**Comment by squakez** [comment]
Part of #5090 - @lburgazzoli can you please have a look and confirm this part is fine. The aim is to manage the SB secret as any other application secret. Thanks.

**Comment by lburgazzoli** [comment]
It's been long time so it look good but wonder if you have an example about how it works as today and how it will change.

**Comment by squakez** [comment]
> It's been long time so it look good but wonder if you have an example about how it works as today and how it will change.

Logic does not change. Instead of performing the secret mount in `pkg/trait/trait_types.go` it does it via the `mount` trait as for the rest of secrets.

**Comment by lburgazzoli** [comment]
so LGTM

@johnpoth WDYT ?

**Pull request merged**
