### PR TITLE
[WIP] Add support for different registries for Kaniko publisher

### PR DESCRIPTION
**Pull request by DarioSwain**
Possible solution for issue: https://github.com/apache/camel-k/issues/613

Please use this PR only as an example.

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Thanks for your PR. I think there should be something more to make it work, but the direction seems good.

One thing I don't understand in Kaniko doc is how it recognizes which secret to use for pushing. In the example you've linked, it mounts the AWS secret into `/root/.aws`. Do we have to do something like this for custom registries?

What tells kaniko to look into `/root/.aws`? Is it something in the json config file?

**Comment by lburgazzoli** [comment]
@nicolaferraro my understanding is that kaniko provides support for some [credential helpers](docker/docker-credential-helpers) by default that are activated by docker's config.json. 

To support pushing to different registries from the kaniko build, I think we need to support the definition of arbitrary configmap/secrets to be mounted in the build configuration spec.

**Comment by davsclaus** [comment]
This PR is half year old. What is the status? Or should it be closed?

**Comment by nicolaferraro** [comment]
This has been implemented in #1084

**Pull request closed without merging**
