### PR TITLE
Enhance Http proxy test about the OLM

### PR DESCRIPTION
**Pull request by bouskaJ**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by bouskaJ** [comment]
The test passed locally. Can you rerun failed pipelines if there is no ongoing issue with the CI on 1.8 branch?

**Comment by squakez** [comment]
> @squakez do you know why we are getting
> 
> ```
> Error:  Failed to execute goal on project camel-k-runtime-builder: Could not resolve dependencies for project org.apache.camel.k:camel-k-runtime-builder:jar:1.0.0: The following artifacts could not be resolved: org.apache.camel.k:camel-k-kamelet-reify:jar:1.12.0, org.apache.camel.k:camel-k-kamelet-reify-deployment:jar:1.12.0: Could not find artifact org.apache.camel.k:camel-k-kamelet-reify:jar:1.12.0 in staging (https://repository.apache.org/content/repositories/orgapachecamel-1411/) -> [Help 1]
> ```
> 
> from the CI?

Can you please rebase? let's see if that is enough to fix

**Comment by squakez** [comment]
Please rebase, the underlying tekton problem should have been fixed in the `release-1.8.x` branch.

**Comment by squakez** [comment]
Merging as errors appears to be related to #3191

**Pull request merged**
