### PR TITLE
fix(examples): add --dependency=camel-rest to usage comments in rest examples

### PR DESCRIPTION
**Pull request by tadayosi**

### CODE REVIEW

**Comment by dmvolod** [comment]
@tadayosi , @nicolaferraro , @lburgazzoli what do you think about automatically add --dependency=camel-rest in case of --open-api option using?

**Comment by oscerd** [comment]
> @tadayosi , @nicolaferraro , @lburgazzoli , @oscerd what do you think about automatically add --dependency=camel-rest in case of --open-api option using?

I'm +1.

**Comment by lburgazzoli** [comment]
+1

**Comment by davsclaus** [comment]
You can also check if rest-dsl is in use, such as these methods are used in the route builder class

   restConfiguration()
   rest()

I think we added a hystrix check to automatic add camel-hystrix. So maybe we can do something similar for this and add camel-rest for above.

**Pull request merged**
