### PR TITLE
CLI - Make kamel run handle github urls that are not raw

### LINKED ISSUE #1497: CLI - Make kamel run handle github urls that are not raw
For example if you browse code on github you may see this example

https://github.com/apache/camel-k/blob/master/examples/hello.xml

And then want to run it via

    kamel run https://github.com/apache/camel-k/blob/master/examples/hello.xml

But it requires the raw url

    kamel run https://raw.githubusercontent.com/apache/camel-k/master/examples/hello.xml

We could maybe make the kamel run command detect the github url and automatic transform the url to the raw url so it can download the source correctly (eg github.com /blob/  -> raw style)

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #1497

**Release Note**
```release-note
It is now possible to run integrations from GitHub with a dedicated URL
syntax:

    kamel run github:$user/$repo/$path?branch=$branch


As example, running the following command

    kamel run github:apache/camel-k/examples/Sample.java

is equivalent to:

    kamel run https://raw.githubusercontent.com/apache/camel-k/master/examples/Sample.java

but does not require to type the full GitHub RAW URL.

Declaring the branch query param is not required and defaults to `master` if not
explicit set.

```

### CODE REVIEW

**Comment by oscerd** [comment]
Wonderful

**Comment by davsclaus** [comment]
awesome lovely work

**Comment by lburgazzoli** [comment]
looks like the travis-ci check is not updated as the related jobs did succeed, see https://travis-ci.org/github/apache/camel-k/builds/696845748

**Comment by nicolaferraro** [comment]
> looks like the travis-ci check is not updated as the related jobs did succeed, see https://travis-ci.org/github/apache/camel-k/builds/696845748
> 
> @nicolaferraro shall we merge this ?

Yes, notifications are not working properly recently.

**Pull request merged**
