### PR TITLE
feat(#5354): Allow adding toleration into builder pod

### PR DESCRIPTION
**Pull request by vkrejcirik**
Closes: #5354 

**Release Note**
```release-note
feat: Allow defining tolerations for Builder pod.
```

### CODE REVIEW

**Review by squakez — COMMENTED** [review]
Thanks for the work. I think it would be better to reuse the same approach we've used for Integrations' tolerations. See https://github.com/apache/camel-k/blob/main/pkg/apis/camel/v1/trait/toleration.go - you may reuse entirely the same logic. Ideally we should provide the concept of taint, and have a way to express it in the same syntax so it is easier from CLI to set via `-t builder.taint=...` (which should also the way we unit test it).

**Comment by squakez** [comment]
BTW, also better to squash the commits into a single one in order to have a cleaner history.

**Comment by squakez** [comment]
Maybe some alternative approach would be to work directly on the Toleration trait, having an additional option like `-t toleration.pipeline-taint=...` and have all the logic encapsulated in a single place. In the same way we may rework the affinity etc.

**Comment by vkrejcirik** [comment]
> Thanks for the work. I think it would be better to reuse the same approach we've used for Integrations' tolerations. See https://github.com/apache/camel-k/blob/main/pkg/apis/camel/v1/trait/toleration.go - you may reuse entirely the same logic. Ideally we should provide the concept of taint, and have a way to express it in the same syntax so it is easier from CLI to set via `-t builder.taint=...` (which should also the way we unit test it).

I was essentially following the approach from #4968 as we discussed. I like the approach of extending Toleration trait with new option for Builder pod and having the logic in a single place. So, if we are on the same page and that's what you prefer, I can look into adding this functionality there.

Thanks

**Comment by squakez** [comment]
Any update on this development? I'd like to understand if it may be ready to be included in 2.4.0 (https://github.com/apache/camel-k/issues/5678)

**Comment by vkrejcirik** [comment]
Im currently busy with our client. We are finishing project. I would like to pick up on this next or following week. I apologize for delay.

**Comment by squakez** [comment]
> Im currently busy with our client. We are finishing project. I would like to pick up on this next or following week. I apologize for delay.

No problem, there's no hurry. I understand that if it does not make in time for 2.4 will be fine to defer for 2.5.

**Pull request closed without merging**
