### PR TITLE
fix(build): complete repo name for default baseImage

### PR DESCRIPTION
**Pull request by gansheer**
## Motivation

The baseImage is repository partially complete. To be correct we need to have the full name or the short name.

## Description

Remove the `docker.io` part into the repository name for the baseImage.
Add some code to manage the Buildah publish strategy's default baseImage that needs a full name. In case of override of the default baseImage the user is in charge of ensuring it is valid.

**Release Note**
```release-note
fix: Shorten baseImage declaration to eclipse-temurin:11 and manage Buildah publish strategy
```

### CODE REVIEW

**Review by squakez — COMMENTED** [review]
I am not really sure if that would be the correct way to pull the image from Docker Hub catalog. According to the Docker documentation, the path should be even without the `docker.io` [1] as it assumes by default that is the registry to use. Is it required by any chance in some kubernetes cluster like OCP?

[1] https://docs.docker.com/engine/reference/commandline/pull/#pull-from-a-different-registry

**Comment by gansheer** [comment]
> I am not really sure if that would be the correct way to pull the image from Docker Hub catalog. According to the Docker documentation, the path should be even without the `docker.io` [1] as it assumes by default that is the registry to use. Is it required by any chance in some kubernetes cluster like OCP?
> 
> [1] https://docs.docker.com/engine/reference/commandline/pull/#pull-from-a-different-registry

The `docker.io` part was introduced by this [PR#3309](https://github.com/apache/camel-k/pull/3309), so I guess Buildah needs it. I could try to remove the `docker.io` if we think we have enough tests for Buildah (and multi-architecture).

**Comment by squakez** [comment]
Yeah, let's try removing the domain name and see if the default is good enough also for other publish strategies. If it does not work, we should instead apply any specific logic to the affected publishing strategy.

**Comment by gansheer** [comment]
@squakez @oscerd @christophd can one of you trigger the workflow please :smile:

**Comment by squakez** [comment]
I've restarted the failing checks now that the actions are back stable. If all is green, is this good to merge?

**Pull request merged**
