### PR TITLE
[TEST] OLM fresh install test

### PR DESCRIPTION
**Pull request by bouskaJ**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by bouskaJ** [comment]
This test is implemented to check the OLM installation (mainly the correctness of the installed operator image). I am not sure whether it fits to the upgrade test but it's the only workflow with the OLM installation and I don't want to create a new one for this purpose.

**Review by phantomjinx — APPROVED** [review]
LGTM

**Review by tadayosi — APPROVED** [review]

**Comment by tadayosi** [comment]
> This test is implemented to check the OLM installation (mainly the correctness of the installed operator image). I am not sure whether it fits to the upgrade test but it's the only workflow with the OLM installation and I don't want to create a new one for this purpose.

@bouskaJ I wonder why it cannot fit into e2e/namespace/install?  Other than the install test suite is already bloated, it seems to be a more proper location.

**Comment by bouskaJ** [comment]
> 

This test is focused on the OLM installation. I can't see the OLM installation step in the install test suite so I assume that it will not work under the `install` workflow environment.

**Comment by tadayosi** [comment]
@phantomjinx Doesn't olm test work under e2e/namespace/install?  If it only works under e2e/namespace/upgrade maybe we should change the name from 'upgrade' to 'olm'.

**Comment by bouskaJ** [comment]
> @phantomjinx Doesn't olm test work under e2e/namespace/install? If it only works under e2e/namespace/upgrade maybe we should change the name from 'upgrade' to 'olm'.

We have two kinds of the tests in the `upgrade` folder
- [cli_upgrade_test.go](https://github.com/apache/camel-k/blob/main/e2e/namespace/upgrade/cli_upgrade_test.go) - test the upgrade without the OLM
- [olm_upgrade_test.go](https://github.com/apache/camel-k/blob/main/e2e/namespace/upgrade/olm_upgrade_test.go) - OLM focused upgrade test

As you can see that is not the OLM only workflow. I don't know how to approach this.

**Comment by tadayosi** [comment]
OK, and right now OLM is available only under `e2e/namespace/upgrade`. Let's accept this PR as-is now. We should rename the e2e structure later.

**Pull request merged**
