### PR TITLE
File changes after running make

### PR DESCRIPTION
**Pull request by doru1004**
Changes to files after building kamel locally.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by doru1004** [comment]
Not sure how to categorize this sort of changes but they seem to occur after running make.

**Comment by nicolaferraro** [comment]
I think the root cause may be this: https://github.com/apache/camel-k-runtime/issues/576

For some reason the json produced by the runtime plugin is no longer sorted.

**Comment by doru1004** [comment]
So I think https://github.com/apache/camel-k-runtime/pull/584 now resolves this problem. If so I'll close this PR.

**Comment by nicolaferraro** [comment]
After switching to snapshot, this seems not to happen

**Pull request closed without merging**
