### PR TITLE
fix(ci): CRD dependency release in action

### PR DESCRIPTION
**Pull request by squakez**
**Release Note**
```release-note
fix(ci): CRD dependency release in action
```

### CODE REVIEW

**Comment by squakez** [comment]
FYI @andreaTP

**Review by oscerd — APPROVED** [review]

**Comment by squakez** [comment]
Check validation not required for this change. Merging.

**Comment by andreaTP** [comment]
🎉  can you give me a link to the first CI that runs this?

**Comment by squakez** [comment]
Sure. This is going to run nightly as last step of the snapshot release process: https://github.com/apache/camel-k/actions/workflows/release.yml - I expect some failures at the beginning, so, we'll be making change until it finally works (feel free to make any change you see they are needed). Once the snapshot are released, we'll use the process to do the fixed release as well.

**Comment by andreaTP** [comment]
Sounds like a plan 🚀

**Pull request merged**
